// trust-router/ownership_encoding.rs: Certus-specific ownership axiom SMT generation
//
// tRust: #178 Generates enriched SMT-LIB2 scripts for certus that embed:
// - Region non-aliasing axioms (from region_encoding.rs patterns)
// - Borrow validity constraints
// - Stacked Borrows permission assertions
// - Lifetime outlives relations
//
// When a VC carries ownership semantics (detected by [memory:region] prefix in
// VcKind::Assertion messages), certus uses this module instead of the plain
// generate_smtlib_script() from smtlib_backend.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use trust_types::*;
use std::fmt::Write;

use crate::smtlib_backend::generate_smtlib_script;

/// tRust: #178 Ownership VC sub-kinds for certus dispatch and diagnostics.
///
/// Classifies the specific ownership property being verified. Used by
/// `can_handle()` to accept ownership VCs, and by the SMT encoding to
/// select appropriate axiom templates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub(crate) enum OwnershipVcKind {
    /// Two exclusive regions must have distinct base addresses.
    MutExclusivity,
    /// Accessing a value after it has been moved out.
    UseAfterMove,
    /// Accessing a value after it has been dropped.
    UseAfterDrop,
    /// A borrow outlives its parent region.
    BorrowLifetime,
    /// A shared reference is read-only (no mutation through &T).
    SharedReadOnly,
    /// Two regions must not alias.
    NonAliasing,
    /// Raw pointer provenance violation (addr_of / pointer cast).
    ProvenanceViolation,
}

impl OwnershipVcKind {
    /// Human-readable label for SMT comments.
    pub(crate) fn label(self) -> &'static str {
        match self {
            OwnershipVcKind::MutExclusivity => "mut-exclusivity",
            OwnershipVcKind::UseAfterMove => "use-after-move",
            OwnershipVcKind::UseAfterDrop => "use-after-drop",
            OwnershipVcKind::BorrowLifetime => "borrow-lifetime",
            OwnershipVcKind::SharedReadOnly => "shared-read-only",
            OwnershipVcKind::NonAliasing => "non-aliasing",
            OwnershipVcKind::ProvenanceViolation => "provenance-violation",
        }
    }
}

/// tRust: #178 Detect whether a VC is an ownership-related VC.
///
/// Returns `true` for VCs generated by trust-vcgen/region_encoding.rs which
/// use VcKind::Assertion with a `[memory:region]` prefix.
#[must_use]
pub(crate) fn is_ownership_vc(vc: &VerificationCondition) -> bool {
    match &vc.kind {
        VcKind::Assertion { message } => message.starts_with("[memory:region]"),
        _ => false,
    }
}

/// tRust: #178 Classify an ownership VC into its specific sub-kind.
///
/// Parses the `[memory:region]` assertion message to determine the exact
/// ownership property being checked.
#[must_use]
pub(crate) fn classify_ownership_vc(vc: &VerificationCondition) -> Option<OwnershipVcKind> {
    let message = match &vc.kind {
        VcKind::Assertion { message } if message.starts_with("[memory:region]") => message,
        _ => return None,
    };

    // region_encoding.rs generates these specific message patterns:
    if message.contains("non-aliasing") {
        Some(OwnershipVcKind::NonAliasing)
    } else if message.contains("multiple mutable borrows")
        || (message.contains("shared borrow") && message.contains("mutable borrow"))
    {
        Some(OwnershipVcKind::MutExclusivity)
    } else if message.contains("use after move") {
        Some(OwnershipVcKind::UseAfterMove)
    } else if message.contains("borrows from dropped") {
        Some(OwnershipVcKind::UseAfterDrop)
    } else if message.contains("borrows from moved")
        || message.contains("borrow outlives parent")
        || message.contains("dangling borrow")
    {
        Some(OwnershipVcKind::BorrowLifetime)
    } else if message.contains("provenance") {
        Some(OwnershipVcKind::ProvenanceViolation)
    } else {
        // Unknown ownership sub-kind; still ownership-related.
        Some(OwnershipVcKind::NonAliasing)
    }
}

/// tRust: #193 Check whether a formula references region or provenance variables.
///
/// Returns `true` if any Var node has a name starting with `region_` or
/// `provenance_`. Used to gate axiom injection: ownership axioms should only
/// be emitted when the VC actually uses region/provenance-level concepts,
/// preventing confusing axiom pollution when the VC is dispatched to backends
/// that do not understand ownership (e.g., zani BMC).
#[must_use]
pub(crate) fn formula_references_regions(formula: &Formula) -> bool {
    let mut found = false;
    formula.visit(&mut |node| {
        if found {
            return;
        }
        if let Formula::Var(name, _) = node
            && (name.starts_with("region_") || name.starts_with("provenance_")) {
                found = true;
            }
    });
    found
}

/// tRust: #193 Wrap an SMT axiom assertion in a provenance guard.
///
/// Instead of asserting `axiom` unconditionally, wraps it as:
///   `(assert (=> (has_provenance <region>) <axiom_body>))`
///
/// This ensures that backends which do not track provenance (like zani BMC)
/// treat the axiom as vacuously true, avoiding unsound interactions.
fn provenance_guarded_assert(region_id: &str, axiom_body: &str) -> String {
    format!(
        "(assert (=> {region_id}_live {axiom_body})) ; guarded: only when {region_id} is live\n"
    )
}

/// tRust: #178 Extract region identifiers from a VC's formula.
///
/// Scans Var nodes for names matching the `region_*_base` or `region_*_val`
/// patterns emitted by region_encoding.rs.
fn extract_region_ids(formula: &Formula) -> Vec<String> {
    let mut regions = Vec::new();
    formula.visit(&mut |node| {
        if let Formula::Var(name, _) = node {
            // region_encoding.rs uses "region_N_base" and "region_N_val" patterns.
            if let Some(prefix) = name.strip_suffix("_base") {
                if prefix.starts_with("region_") {
                    regions.push(prefix.to_string());
                }
            } else if let Some(prefix) = name.strip_suffix("_val")
                && prefix.starts_with("region_") && !regions.contains(&prefix.to_string()) {
                    regions.push(prefix.to_string());
                }
        }
    });
    regions.sort();
    regions.dedup();
    regions
}

/// tRust: #178 Generate an enriched SMT-LIB2 script with ownership axioms.
///
/// Wraps the standard SMT-LIB2 script with certus-specific ownership axioms:
/// 1. Region non-aliasing axioms for exclusive regions
/// 2. Borrow validity constraints (parent liveness)
/// 3. Stacked Borrows permission assertions (Write/Read/Disabled)
/// 4. Lifetime outlives relations
///
/// Falls back to the standard script if the VC has no ownership metadata.
#[must_use]
pub(crate) fn generate_ownership_enriched_script(vc: &VerificationCondition) -> String {
    let ownership_kind = classify_ownership_vc(vc);
    let region_ids = extract_region_ids(&vc.formula);

    // Start with the base SMT-LIB2 encoding.
    let base_script = generate_smtlib_script(&vc.formula);

    let mut script = String::with_capacity(base_script.len() + 1024);

    // -- Certus header ---------------------------------------------------
    script.push_str("; certus ownership-aware verification\n");
    script.push_str("(set-option :ownership-mode true)\n");
    script.push_str("(set-option :borrow-check true)\n");
    script.push_str("(set-option :stacked-borrows true)\n");

    if let Some(kind) = ownership_kind {
        let _ = writeln!(script, "; certus ownership kind: {}", kind.label());
    }

    // tRust: #193 Only inject ownership axioms when the formula actually
    // references region/provenance variables. Without this guard, backends
    // like zani (BMC) receive axioms about variables they never declared,
    // causing confusing errors or unsound results.
    let has_regions = !region_ids.is_empty();

    if has_regions {
        // -- Borrow validity constraints (declared early so guards can reference them) --
        script.push_str("\n; === Borrow validity constraints ===\n");
        for region in &region_ids {
            // Declare a liveness variable for each region (certus uses these).
            let _ = writeln!(script, 
                "(declare-const {region}_live Bool) ; region liveness"
            );
        }

        // -- Region non-aliasing axioms (provenance-guarded) ------------------
        // For each pair of distinct regions, assert their base addresses differ,
        // but only when both regions are live (provenance guard).
        if region_ids.len() >= 2 {
            script.push_str("\n; === Region non-aliasing axioms (provenance-guarded) ===\n");
            for i in 0..region_ids.len() {
                for j in (i + 1)..region_ids.len() {
                    // tRust: #193 Guarded: only assert non-aliasing when both regions are live.
                    let _ = writeln!(script, 
                        "(assert (=> (and {r1}_live {r2}_live) (distinct {r1}_base {r2}_base))) ; {r1} != {r2} (guarded)",
                        r1 = region_ids[i],
                        r2 = region_ids[j],
                    );
                }
            }
        }

        // -- Stacked Borrows permission layer (provenance-guarded) -----------
        // Each region has a permission level: Write (2), Read (1), Disabled (0).
        // &mut T => Write, &T => Read, moved/dropped => Disabled.
        script.push_str("\n; === Stacked Borrows permission model (provenance-guarded) ===\n");
        for region in &region_ids {
            let _ = writeln!(script, 
                "(declare-const {region}_perm Int) ; 0=Disabled 1=Read 2=Write"
            );
            // Permissions are bounded, guarded by liveness.
            script.push_str(&provenance_guarded_assert(
                region,
                &format!("(and (>= {region}_perm 0) (<= {region}_perm 2))"),
            ));
        }

        // Write-permission exclusivity: at most one Write per parent.
        if region_ids.len() >= 2 {
            script.push_str("; Write-exclusivity: at most one region with Write per parent (guarded)\n");
            for i in 0..region_ids.len() {
                for j in (i + 1)..region_ids.len() {
                    // tRust: #193 Guard with both regions live.
                    let _ = writeln!(script, 
                        "(assert (=> (and {r1}_live {r2}_live) (not (and (= {r1}_perm 2) (= {r2}_perm 2))))) ; no double Write (guarded)",
                        r1 = region_ids[i],
                        r2 = region_ids[j],
                    );
                }
            }

            // Read/Write conflict: if one has Write, others cannot have Read.
            script.push_str("; Read/Write exclusion (guarded)\n");
            for i in 0..region_ids.len() {
                for j in 0..region_ids.len() {
                    if i != j {
                        let _ = writeln!(script, 
                            "(assert (=> (and {r1}_live {r2}_live) (=> (= {r1}_perm 2) (not (= {r2}_perm 1))))) ; Write({r1}) => not Read({r2}) (guarded)",
                            r1 = region_ids[i],
                            r2 = region_ids[j],
                        );
                    }
                }
            }
        }

        // -- Lifetime outlives relations (provenance-guarded) ----------------
        // Encode as implication: if child is live, parent must be live.
        script.push_str("\n; === Lifetime outlives constraints ===\n");
        // Ownership kind-specific lifetime axioms.
        if let Some(OwnershipVcKind::BorrowLifetime) = ownership_kind {
            // For borrow lifetime VCs, encode that borrows cannot outlive parents.
            for region in &region_ids {
                let _ = writeln!(script, 
                    "; (assert (=> {region}_live parent_live)) ; borrow outlives check"
                );
            }
        }
    } else {
        // tRust: #193 No region variables in formula — skip ownership axioms entirely.
        script.push_str("\n; === No region/provenance variables detected — ownership axioms skipped ===\n");
    }

    // -- Base script (declarations + assertions + check-sat) -------------
    script.push_str("\n; === Base verification condition ===\n");
    script.push_str(&base_script);

    script
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_ownership_vc(message: &str, formula: Formula) -> VerificationCondition {
        VerificationCondition {
            kind: VcKind::Assertion { message: message.to_string() },
            function: "test_fn".to_string(),
            location: SourceSpan::default(),
            formula,
            contract_metadata: None,
        }
    }

    // -- is_ownership_vc tests -------------------------------------------

    #[test]
    fn test_is_ownership_vc_with_region_prefix() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Bool(true),
        );
        assert!(is_ownership_vc(&vc));
    }

    #[test]
    fn test_is_ownership_vc_without_prefix() {
        let vc = VerificationCondition {
            kind: VcKind::DivisionByZero,
            function: "test".to_string(),
            location: SourceSpan::default(),
            formula: Formula::Bool(true),
            contract_metadata: None,
        };
        assert!(!is_ownership_vc(&vc));
    }

    #[test]
    fn test_is_ownership_vc_non_memory_assertion() {
        let vc = make_ownership_vc("some other assertion", Formula::Bool(true));
        assert!(!is_ownership_vc(&vc));
    }

    // -- classify_ownership_vc tests -------------------------------------

    #[test]
    fn test_classify_non_aliasing() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 (owned) vs region_1 (owned)",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::NonAliasing));
    }

    #[test]
    fn test_classify_multiple_mutable_borrows() {
        let vc = make_ownership_vc(
            "[memory:region] multiple mutable borrows: region_1 and region_2 both borrow region_0",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::MutExclusivity));
    }

    #[test]
    fn test_classify_shared_and_mutable_conflict() {
        let vc = make_ownership_vc(
            "[memory:region] shared borrow region_2 coexists with mutable borrow region_1 of region_0",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::MutExclusivity));
    }

    #[test]
    fn test_classify_use_after_move() {
        let vc = make_ownership_vc(
            "[memory:region] use after move: local _0 was moved",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::UseAfterMove));
    }

    #[test]
    fn test_classify_borrow_from_dropped() {
        let vc = make_ownership_vc(
            "[memory:region] borrow outlives parent: region_1 borrows from dropped region_0",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::UseAfterDrop));
    }

    #[test]
    fn test_classify_dangling_borrow() {
        let vc = make_ownership_vc(
            "[memory:region] dangling borrow: region_1 borrows from non-existent parent region_0",
            Formula::Bool(true),
        );
        assert_eq!(classify_ownership_vc(&vc), Some(OwnershipVcKind::BorrowLifetime));
    }

    #[test]
    fn test_classify_non_ownership_vc_returns_none() {
        let vc = VerificationCondition {
            kind: VcKind::DivisionByZero,
            function: "test".to_string(),
            location: SourceSpan::default(),
            formula: Formula::Bool(true),
            contract_metadata: None,
        };
        assert_eq!(classify_ownership_vc(&vc), None);
    }

    // -- extract_region_ids tests ----------------------------------------

    #[test]
    fn test_extract_region_ids_from_formula() {
        let formula = Formula::Eq(
            Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
            Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
        );
        let ids = extract_region_ids(&formula);
        assert_eq!(ids, vec!["region_0", "region_1"]);
    }

    #[test]
    fn test_extract_region_ids_with_val_suffix() {
        let formula = Formula::Var("region_0_val".to_string(), Sort::Int);
        let ids = extract_region_ids(&formula);
        assert_eq!(ids, vec!["region_0"]);
    }

    #[test]
    fn test_extract_region_ids_deduplicates() {
        let formula = Formula::And(vec![
            Formula::Var("region_0_base".to_string(), Sort::Int),
            Formula::Var("region_0_val".to_string(), Sort::Int),
            Formula::Var("region_1_base".to_string(), Sort::Int),
        ]);
        let ids = extract_region_ids(&formula);
        assert_eq!(ids, vec!["region_0", "region_1"]);
    }

    #[test]
    fn test_extract_region_ids_no_regions() {
        let formula = Formula::Var("x".to_string(), Sort::Int);
        let ids = extract_region_ids(&formula);
        assert!(ids.is_empty());
    }

    // -- generate_ownership_enriched_script tests ------------------------

    #[test]
    fn test_enriched_script_contains_ownership_headers() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
                Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        assert!(script.contains("; certus ownership-aware verification"));
        assert!(script.contains("(set-option :ownership-mode true)"));
        assert!(script.contains("(set-option :borrow-check true)"));
        assert!(script.contains("(set-option :stacked-borrows true)"));
        assert!(script.contains("; certus ownership kind: non-aliasing"));
    }

    #[test]
    fn test_enriched_script_contains_non_aliasing_axioms_guarded() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
                Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        assert!(script.contains("Region non-aliasing axioms"));
        // tRust: #193 Non-aliasing axioms are now provenance-guarded.
        assert!(script.contains("(assert (=> (and region_0_live region_1_live) (distinct region_0_base region_1_base)))"));
    }

    #[test]
    fn test_enriched_script_contains_stacked_borrows_guarded() {
        let vc = make_ownership_vc(
            "[memory:region] multiple mutable borrows: region_1 and region_2 both borrow region_0",
            Formula::And(vec![
                Formula::Var("region_1_base".to_string(), Sort::Int),
                Formula::Var("region_2_base".to_string(), Sort::Int),
            ]),
        );

        let script = generate_ownership_enriched_script(&vc);

        assert!(script.contains("Stacked Borrows permission model (provenance-guarded)"));
        assert!(script.contains("region_1_perm"));
        assert!(script.contains("region_2_perm"));
        // tRust: #193 Write exclusivity is now provenance-guarded.
        assert!(script.contains("no double Write (guarded)"));
    }

    #[test]
    fn test_enriched_script_contains_base_vc() {
        let formula = Formula::Eq(
            Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
            Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
        );
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            formula,
        );

        let script = generate_ownership_enriched_script(&vc);

        // Must contain the base script elements.
        assert!(script.contains("(check-sat)"));
        assert!(script.contains("(declare-const region_0_base Int)"));
        assert!(script.contains("(assert (= region_0_base region_1_base))"));
    }

    #[test]
    fn test_enriched_script_for_non_ownership_vc_still_works() {
        let vc = VerificationCondition {
            kind: VcKind::DivisionByZero,
            function: "test".to_string(),
            location: SourceSpan::default(),
            formula: Formula::Bool(false),
            contract_metadata: None,
        };

        let script = generate_ownership_enriched_script(&vc);

        // Should still generate a valid script (with ownership headers but no regions).
        assert!(script.contains("(set-option :ownership-mode true)"));
        assert!(script.contains("(check-sat)"));
        // tRust: #193 No region axioms since no regions detected; skip message present.
        assert!(!script.contains("Region non-aliasing axioms"));
        assert!(script.contains("ownership axioms skipped"));
    }

    #[test]
    fn test_enriched_script_permission_bounds_guarded() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
                Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        // tRust: #193 Permission bounds are now guarded by liveness.
        assert!(script.contains("(assert (=> region_0_live (and (>= region_0_perm 0) (<= region_0_perm 2))))"));
        assert!(script.contains("(assert (=> region_1_live (and (>= region_1_perm 0) (<= region_1_perm 2))))"));
    }

    #[test]
    fn test_enriched_script_liveness_declarations() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
                Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        assert!(script.contains("(declare-const region_0_live Bool)"));
        assert!(script.contains("(declare-const region_1_live Bool)"));
    }

    // -- #193 formula_references_regions tests ----------------------------

    #[test]
    fn test_formula_references_regions_with_region_vars() {
        let formula = Formula::Eq(
            Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
            Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
        );
        assert!(formula_references_regions(&formula));
    }

    #[test]
    fn test_formula_references_regions_with_provenance_vars() {
        let formula = Formula::Var("provenance_tag_0".to_string(), Sort::Int);
        assert!(formula_references_regions(&formula));
    }

    #[test]
    fn test_formula_references_regions_without_region_vars() {
        let formula = Formula::Eq(
            Box::new(Formula::Var("x".to_string(), Sort::Int)),
            Box::new(Formula::Int(42)),
        );
        assert!(!formula_references_regions(&formula));
    }

    #[test]
    fn test_formula_references_regions_nested() {
        let formula = Formula::And(vec![
            Formula::Gt(
                Box::new(Formula::Var("x".to_string(), Sort::Int)),
                Box::new(Formula::Int(0)),
            ),
            Formula::Lt(
                Box::new(Formula::Var("region_2_val".to_string(), Sort::Int)),
                Box::new(Formula::Int(100)),
            ),
        ]);
        assert!(formula_references_regions(&formula));
    }

    #[test]
    fn test_formula_references_regions_bool_literal() {
        assert!(!formula_references_regions(&Formula::Bool(true)));
    }

    // -- #193 provenance guard tests --------------------------------------

    #[test]
    fn test_provenance_guarded_assert_format() {
        let result = provenance_guarded_assert("region_0", "(> region_0_perm 0)");
        assert!(result.contains("(assert (=> region_0_live (> region_0_perm 0)))"));
        assert!(result.contains("guarded: only when region_0 is live"));
    }

    // -- #193 conditional axiom injection tests ---------------------------

    #[test]
    fn test_enriched_script_skips_axioms_for_non_region_formula() {
        // Ownership VC by message, but formula has no region/provenance variables.
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("x".to_string(), Sort::Int)),
                Box::new(Formula::Int(42)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        // Headers still present (certus options).
        assert!(script.contains("(set-option :ownership-mode true)"));
        // But no axioms injected since formula lacks region variables.
        assert!(script.contains("ownership axioms skipped"));
        assert!(!script.contains("Region non-aliasing axioms"));
        assert!(!script.contains("Stacked Borrows"));
    }

    #[test]
    fn test_enriched_script_non_aliasing_guard_requires_both_live() {
        let vc = make_ownership_vc(
            "[memory:region] non-aliasing: region_0 vs region_1",
            Formula::Eq(
                Box::new(Formula::Var("region_0_base".to_string(), Sort::Int)),
                Box::new(Formula::Var("region_1_base".to_string(), Sort::Int)),
            ),
        );

        let script = generate_ownership_enriched_script(&vc);

        // Non-aliasing must be guarded by both regions being live.
        assert!(script.contains("(=> (and region_0_live region_1_live) (distinct region_0_base region_1_base))"));
    }

    #[test]
    fn test_enriched_script_write_exclusivity_guarded() {
        let vc = make_ownership_vc(
            "[memory:region] multiple mutable borrows: region_0 and region_1",
            Formula::And(vec![
                Formula::Var("region_0_base".to_string(), Sort::Int),
                Formula::Var("region_1_base".to_string(), Sort::Int),
            ]),
        );

        let script = generate_ownership_enriched_script(&vc);

        // Write exclusivity must be guarded by both regions being live.
        assert!(script.contains(
            "(assert (=> (and region_0_live region_1_live) (not (and (= region_0_perm 2) (= region_1_perm 2)))))"
        ));
    }
}
