// trust-router/solver_cache.rs: VC-level solver result caching
//
// Wraps the Router to intercept verify_one/verify_all calls and check a
// ResultCache before dispatching to backends. Cache key is (formula_hash,
// solver_name) — the same VC sent to the same solver returns the cached
// result without invoking the solver.
//
// tRust #520: Wire trust-cache into production verification path.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use std::fmt::Write as FmtWrite;
use std::sync::Mutex;

use trust_types::{ProofStrength, VerificationCondition, VerificationResult};

// tRust #527: Import from trust-cache (canonical location) instead of crate re-export.
use crate::Router;
use trust_cache::result_cache::{
    CachePolicy, CacheStats, CachedResult, ResultCache, ResultCacheKey, hash_formula,
};

/// Compute a deterministic SHA-256 hash of a `VerificationCondition`'s formula.
///
/// Uses the canonical SMT-LIB2 representation of the formula, which is stable
/// across compiler versions (unlike `Debug` repr). SHA-256 provides collision
/// resistance to ~2^128, preventing cache collisions that could return incorrect
/// verdicts. See #692, #754.
#[must_use]
pub fn vc_formula_hash(vc: &VerificationCondition) -> String {
    let smt_repr = vc.formula.to_smtlib();
    hash_formula(&smt_repr)
}

/// Convert a `VerificationResult` to a verdict string for cache storage.
fn verdict_string(result: &VerificationResult) -> &'static str {
    match result {
        VerificationResult::Proved { .. } => "proved",
        VerificationResult::Failed { .. } => "failed",
        VerificationResult::Unknown { .. } => "unknown",
        VerificationResult::Timeout { .. } => "timeout",
        _ => "unknown",
    }
}

/// Convert a `VerificationResult` to an optional model string for cache storage.
fn model_string(result: &VerificationResult) -> Option<String> {
    match result {
        VerificationResult::Failed { counterexample: Some(cex), .. } => Some(format!("{cex:?}")),
        _ => None,
    }
}

/// Extract the `ProofStrength` from a proved result as JSON for cache storage.
///
/// tRust #755: Preserves the original proof strength through the cache
/// instead of always defaulting to `smt_unsat()`.
fn strength_json(result: &VerificationResult) -> Option<String> {
    match result {
        VerificationResult::Proved { strength, .. } => serde_json::to_string(strength).ok(),
        _ => None,
    }
}

/// Convert a cached entry back to a `VerificationResult`.
///
/// Reconstructs the result from the stored verdict, solver name, and timing.
/// Counterexamples are not preserved through the cache (the model string is
/// informational only). This is acceptable because cache hits on Failed
/// results correctly report the failure — the counterexample can be
/// regenerated by re-running the solver if needed.
fn result_from_cached(entry: &CachedResult) -> VerificationResult {
    match entry.verdict.as_str() {
        "proved" => {
            // tRust #755: Restore original ProofStrength from cache if available.
            let strength = entry
                .strength_json
                .as_deref()
                .and_then(|json| serde_json::from_str::<ProofStrength>(json).ok())
                .unwrap_or_else(ProofStrength::smt_unsat);
            VerificationResult::Proved {
                solver: format!("cached:{}", entry.key.solver_name).into(),
                time_ms: 0,
                strength,
                proof_certificate: None,
                solver_warnings: None,
            }
        }
        "failed" => VerificationResult::Failed {
            solver: format!("cached:{}", entry.key.solver_name).into(),
            time_ms: 0,
            counterexample: None,
        },
        "timeout" => VerificationResult::Timeout {
            solver: format!("cached:{}", entry.key.solver_name).into(),
            timeout_ms: entry.time_ms,
        },
        _ => VerificationResult::Unknown {
            solver: format!("cached:{}", entry.key.solver_name).into(),
            time_ms: 0,
            reason: format!("cached result: {}", entry.verdict),
        },
    }
}

/// A Router wrapper that caches solver results at the VC dispatch level.
///
/// Before dispatching a VC to a solver backend, checks the `ResultCache` for
/// a previous result with the same formula hash and solver name. On cache hit,
/// returns the cached result without invoking the solver. On cache miss,
/// dispatches to the solver and stores the result.
///
/// Thread-safe: the inner `ResultCache` is protected by a `Mutex` so that
/// `verify_all_parallel` can share it across threads.
pub struct SolverCachedRouter {
    router: Router,
    cache: Mutex<ResultCache>,
}

impl SolverCachedRouter {
    /// Create a new solver-cached router wrapping the given router.
    #[must_use]
    pub fn new(router: Router, policy: CachePolicy) -> Self {
        Self { router, cache: Mutex::new(ResultCache::new(policy)) }
    }

    /// Create with a pre-populated cache (e.g., loaded from disk).
    #[must_use]
    pub fn with_cache(router: Router, cache: ResultCache) -> Self {
        Self { router, cache: Mutex::new(cache) }
    }

    /// Access the underlying router.
    #[must_use]
    pub fn router(&self) -> &Router {
        &self.router
    }

    /// tRust #676: Get the shared thread pool from the underlying router, if configured.
    #[must_use]
    pub fn thread_pool(&self) -> Option<&std::sync::Arc<rayon::ThreadPool>> {
        self.router.thread_pool()
    }

    /// Return current cache statistics.
    #[must_use]
    pub fn cache_stats(&self) -> CacheStats {
        self.cache.lock().expect("cache mutex poisoned").cache_stats()
    }

    /// Return the number of cached entries.
    #[must_use]
    pub fn cache_entry_count(&self) -> usize {
        self.cache.lock().expect("cache mutex poisoned").entry_count()
    }

    /// Summary string for diagnostics.
    #[must_use]
    pub fn summary(&self) -> String {
        let stats = self.cache_stats();
        let mut s = String::new();
        let _ = write!(
            s,
            "solver-cache: {} entries, {} hits, {} misses",
            stats.total_entries, stats.hits, stats.misses
        );
        if stats.hits + stats.misses > 0 {
            let rate = stats.hits as f64 / (stats.hits + stats.misses) as f64;
            let _ = write!(s, " ({:.0}% hit rate)", rate * 100.0);
        }
        s
    }

    /// Verify a single VC, checking the cache first.
    ///
    /// The cache key is `(formula_hash, solver_name)` where `solver_name` is
    /// determined by the router's backend selection for this VC. If the cache
    /// has a result for this key, it is returned without invoking the solver.
    pub fn verify_one(&self, vc: &VerificationCondition) -> VerificationResult {
        let formula_hash = vc_formula_hash(vc);

        // Determine which backend would handle this VC to get the solver name.
        let plan = self.router.backend_plan(vc);
        let solver_name = plan
            .iter()
            .find(|entry| entry.can_handle)
            .map(|entry| entry.name.to_string())
            .unwrap_or_else(|| "none".to_string());

        let cache_key =
            ResultCacheKey { formula_hash: formula_hash.clone(), solver_name: solver_name.clone() };

        // Check cache.
        {
            let mut cache = self.cache.lock().expect("cache mutex poisoned");
            if let Some(cached) = cache.replay_result(&cache_key) {
                return result_from_cached(cached);
            }
        }

        // Cache miss: dispatch to solver.
        let result = self.router.verify_one(vc);

        // Store result in cache.
        {
            let mut cache = self.cache.lock().expect("cache mutex poisoned");
            cache.cache_result(
                cache_key,
                verdict_string(&result),
                model_string(&result),
                result.time_ms(),
                strength_json(&result),
            );
        }

        result
    }

    /// Verify all VCs, checking the cache for each.
    pub fn verify_all(
        &self,
        vcs: &[VerificationCondition],
    ) -> Vec<(VerificationCondition, VerificationResult)> {
        vcs.iter()
            .map(|vc| {
                let result = self.verify_one(vc);
                (vc.clone(), result)
            })
            .collect()
    }

    /// Verify all VCs with bounded parallelism, checking the cache for each.
    ///
    /// Falls back to sequential for single VCs or `max_threads <= 1`.
    pub fn verify_all_parallel(
        &self,
        vcs: &[VerificationCondition],
        max_threads: usize,
    ) -> Vec<(VerificationCondition, VerificationResult)> {
        if vcs.len() <= 1 || max_threads <= 1 {
            return self.verify_all(vcs);
        }

        // For parallel dispatch, we check cache sequentially for each VC first,
        // collect misses, dispatch misses in parallel, then store results.
        let mut results: Vec<(VerificationCondition, VerificationResult)> =
            Vec::with_capacity(vcs.len());
        let mut cache_miss_indices: Vec<usize> = Vec::new();
        let mut cache_miss_vcs: Vec<VerificationCondition> = Vec::new();

        // Phase 1: Check cache for all VCs.
        {
            let mut cache = self.cache.lock().expect("cache mutex poisoned");
            for (i, vc) in vcs.iter().enumerate() {
                let formula_hash = vc_formula_hash(vc);
                let plan = self.router.backend_plan(vc);
                let solver_name = plan
                    .iter()
                    .find(|entry| entry.can_handle)
                    .map(|entry| entry.name.to_string())
                    .unwrap_or_else(|| "none".to_string());

                let cache_key = ResultCacheKey { formula_hash, solver_name };

                if let Some(cached) = cache.replay_result(&cache_key) {
                    results.push((vc.clone(), result_from_cached(cached)));
                } else {
                    // Placeholder — will be replaced after parallel dispatch.
                    results.push((
                        vc.clone(),
                        VerificationResult::Unknown {
                            solver: "pending".into(),
                            time_ms: 0,
                            reason: "cache miss, pending dispatch".to_string(),
                        },
                    ));
                    cache_miss_indices.push(i);
                    cache_miss_vcs.push(vc.clone());
                }
            }
        }

        // Phase 2: Dispatch cache misses in parallel.
        if !cache_miss_vcs.is_empty() {
            let fresh_results = self.router.verify_all_parallel(&cache_miss_vcs, max_threads);

            // Phase 3: Store results and fill in placeholders.
            let mut cache = self.cache.lock().expect("cache mutex poisoned");
            for (miss_idx, (_, fresh_result)) in cache_miss_indices.iter().zip(fresh_results) {
                let vc = &vcs[*miss_idx];
                let formula_hash = vc_formula_hash(vc);
                let solver_name = fresh_result.solver_name().to_string();
                // Strip "cached:" prefix if present (shouldn't be for fresh results).
                let solver_name =
                    solver_name.strip_prefix("cached:").unwrap_or(&solver_name).to_string();

                let cache_key = ResultCacheKey { formula_hash, solver_name };

                cache.cache_result(
                    cache_key,
                    verdict_string(&fresh_result),
                    model_string(&fresh_result),
                    fresh_result.time_ms(),
                    strength_json(&fresh_result),
                );

                results[*miss_idx].1 = fresh_result;
            }
        }

        results
    }
}

#[cfg(test)]
mod tests {
    use trust_types::*;

    use super::*;
    use crate::mock_backend::MockBackend;

    fn make_vc(formula: Formula) -> VerificationCondition {
        VerificationCondition {
            kind: VcKind::DivisionByZero,
            function: "test".into(),
            location: SourceSpan::default(),
            formula,
            contract_metadata: None,
        }
    }

    // -----------------------------------------------------------------------
    // Basic cache hit/miss
    // -----------------------------------------------------------------------

    #[test]
    fn test_cache_miss_then_hit() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vc = make_vc(Formula::Bool(false));

        // First call: cache miss, dispatches to mock backend.
        let result1 = cached_router.verify_one(&vc);
        assert!(result1.is_proved());
        assert_eq!(result1.solver_name(), "mock");

        // Second call: cache hit.
        let result2 = cached_router.verify_one(&vc);
        assert!(result2.is_proved());
        assert!(
            result2.solver_name().starts_with("cached:"),
            "should be served from cache, got: {}",
            result2.solver_name()
        );

        let stats = cached_router.cache_stats();
        assert_eq!(stats.hits, 1);
        assert_eq!(stats.misses, 1);
    }

    #[test]
    fn test_different_formulas_miss_cache() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vc1 = make_vc(Formula::Bool(false));
        let vc2 = make_vc(Formula::Bool(true));

        cached_router.verify_one(&vc1);
        cached_router.verify_one(&vc2);

        let stats = cached_router.cache_stats();
        assert_eq!(stats.misses, 2, "different formulas should both miss");
        assert_eq!(stats.hits, 0);
    }

    #[test]
    fn test_same_formula_hits_cache() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vc = make_vc(Formula::Bool(false));

        cached_router.verify_one(&vc);
        cached_router.verify_one(&vc);
        cached_router.verify_one(&vc);

        let stats = cached_router.cache_stats();
        assert_eq!(stats.misses, 1, "first call misses");
        assert_eq!(stats.hits, 2, "subsequent calls hit");
    }

    // -----------------------------------------------------------------------
    // Cache policy
    // -----------------------------------------------------------------------

    #[test]
    fn test_never_cache_always_dispatches() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::NeverCache);

        let vc = make_vc(Formula::Bool(false));

        let r1 = cached_router.verify_one(&vc);
        let r2 = cached_router.verify_one(&vc);

        assert_eq!(r1.solver_name(), "mock");
        assert_eq!(r2.solver_name(), "mock"); // NOT cached
        assert_eq!(cached_router.cache_entry_count(), 0);
    }

    // -----------------------------------------------------------------------
    // verify_all
    // -----------------------------------------------------------------------

    #[test]
    fn test_verify_all_uses_cache() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vcs = vec![make_vc(Formula::Bool(false)), make_vc(Formula::Bool(true))];

        // First pass: all miss.
        let results1 = cached_router.verify_all(&vcs);
        assert_eq!(results1.len(), 2);

        // Second pass: all hit.
        let results2 = cached_router.verify_all(&vcs);
        assert_eq!(results2.len(), 2);
        for (_, result) in &results2 {
            assert!(
                result.solver_name().starts_with("cached:"),
                "expected cached result, got: {}",
                result.solver_name()
            );
        }
    }

    // -----------------------------------------------------------------------
    // verify_all_parallel
    // -----------------------------------------------------------------------

    #[test]
    fn test_verify_all_parallel_uses_cache() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vcs: Vec<_> = (0..4).map(|i| make_vc(Formula::Bool(i % 2 == 0))).collect();

        // First pass: 2 unique formulas = 2 misses + 2 hits (duplicates).
        let results1 = cached_router.verify_all_parallel(&vcs, 2);
        assert_eq!(results1.len(), 4);

        // Second pass: all should hit.
        let results2 = cached_router.verify_all_parallel(&vcs, 2);
        assert_eq!(results2.len(), 4);
        for (_, result) in &results2 {
            assert!(result.solver_name().starts_with("cached:"));
        }
    }

    // -----------------------------------------------------------------------
    // Summary
    // -----------------------------------------------------------------------

    #[test]
    fn test_summary_format() {
        let router = Router::with_backends(vec![Box::new(MockBackend)]);
        let cached_router = SolverCachedRouter::new(router, CachePolicy::AlwaysCache);

        let vc = make_vc(Formula::Bool(false));
        cached_router.verify_one(&vc);
        cached_router.verify_one(&vc);

        let summary = cached_router.summary();
        assert!(summary.contains("solver-cache:"));
        assert!(summary.contains("1 entries"));
        assert!(summary.contains("1 hits"));
        assert!(summary.contains("1 misses"));
    }

    // -----------------------------------------------------------------------
    // vc_formula_hash determinism
    // -----------------------------------------------------------------------

    #[test]
    fn test_vc_formula_hash_deterministic() {
        let vc = make_vc(Formula::Gt(
            Box::new(Formula::Var("x".into(), Sort::Int)),
            Box::new(Formula::Int(0)),
        ));

        let h1 = vc_formula_hash(&vc);
        let h2 = vc_formula_hash(&vc);
        assert_eq!(h1, h2, "formula hash must be deterministic");
    }

    #[test]
    fn test_vc_formula_hash_differs_for_different_formulas() {
        let vc1 = make_vc(Formula::Bool(true));
        let vc2 = make_vc(Formula::Bool(false));

        assert_ne!(
            vc_formula_hash(&vc1),
            vc_formula_hash(&vc2),
            "different formulas should have different hashes"
        );
    }
}
