#![deny(unused_variables)]

use anyhow::{Context, Error};
use build_helper::stage0_parser::{Stage0Config, VersionMetadata, parse_stage0_file};
use curl::easy::Easy;
use indexmap::IndexMap;
use sha2::{Digest, Sha256};
use std::path::PathBuf;

const PATH: &str = "src/stage0";
const COMPILER_COMPONENTS: &[&str] = &[
    "rustc",
    "rust-std",
    "cargo",
    "clippy-preview",
    "rustfmt-preview",
    "rust-docs",
    "cargo-trust",
    "rust-analyzer-preview",
    "rust-src",
    "llvm-tools-preview",
];
const RUSTFMT_COMPONENTS: &[&str] = &["rustfmt-preview", "rustc"];

struct Tool {
    config: Stage0Config,

    channel: Channel,
    compiler_date: Option<String>,
    rustfmt_date: Option<String>,
    version: [u16; 3],
    checksums: IndexMap<String, String>,
}

impl Tool {
    fn new(compiler_date: Option<String>, rustfmt_date: Option<String>) -> Result<Self, Error> {
        let channel = match std::fs::read_to_string("src/ci/channel")?.trim() {
            "stable" => Channel::Stable,
            "beta" => Channel::Beta,
            "nightly" => Channel::Nightly,
            other => anyhow::bail!("unsupported channel: {}", other),
        };

        // Split "1.42.0" into [1, 42, 0]
        let version = std::fs::read_to_string("src/version")?
            .trim()
            .split('.')
            .map(|val| val.parse())
            .collect::<Result<Vec<_>, _>>()?
            .try_into()
            .map_err(|_| anyhow::anyhow!("failed to parse version"))?;

        let existing = parse_stage0_file();

        Ok(Self {
            channel,
            version,
            compiler_date,
            rustfmt_date,
            config: existing.config,
            checksums: IndexMap::new(),
        })
    }

    fn update_stage0_file(mut self) -> Result<(), Error> {
        const COMMENTS: &str = r#"# The configuration above this comment is editable, and can be changed
# by forks of the repository if they have alternate values.
#
# The section below is generated by `./x.py run src/tools/bump-stage0`,
# run that command again to update the bootstrap compiler.
#
# All changes below this comment will be overridden the next time the
# tool is executed.
"#;

        let mut file_content = String::new();

        // Destructure `Stage0Config` here to ensure the stage0 file is synced with any new
        // fields when they are added.
        let Stage0Config {
            dist_server,
            artifacts_server,
            artifacts_with_llvm_assertions_server,
            git_merge_commit_email,
            nightly_branch,
            compiler_dist_channel,
            rustfmt_dist_channel,
        } = &self.config;

        file_content.push_str(&format!("dist_server={}\n", dist_server));
        file_content.push_str(&format!("artifacts_server={}\n", artifacts_server));
        file_content.push_str(&format!(
            "artifacts_with_llvm_assertions_server={}\n",
            artifacts_with_llvm_assertions_server
        ));
        file_content.push_str(&format!("git_merge_commit_email={}\n", git_merge_commit_email));
        file_content.push_str(&format!("nightly_branch={}\n", nightly_branch));
        file_content.push_str(&format!("compiler_dist_channel={}\n", compiler_dist_channel));
        file_content.push_str(&format!("rustfmt_dist_channel={}\n", rustfmt_dist_channel));

        file_content.push_str("\n");
        file_content.push_str(COMMENTS);
        file_content.push_str("\n");

        let compiler = self.detect_compiler()?;
        file_content.push_str(&format!(
            "compiler_channel_manifest_hash={}\n",
            compiler.channel_manifest_hash
        ));
        file_content.push_str(&format!("compiler_git_commit_hash={}\n", compiler.git_commit_hash));
        file_content.push_str(&format!("compiler_date={}\n", compiler.date));
        file_content.push_str(&format!("compiler_version={}\n", compiler.version));

        if let Some(rustfmt) = self.detect_rustfmt()? {
            file_content.push_str(&format!(
                "rustfmt_channel_manifest_hash={}\n",
                rustfmt.channel_manifest_hash
            ));
            file_content
                .push_str(&format!("rustfmt_git_commit_hash={}\n", rustfmt.git_commit_hash));
            file_content.push_str(&format!("rustfmt_date={}\n", rustfmt.date));
            file_content.push_str(&format!("rustfmt_version={}\n", rustfmt.version));
        }

        file_content.push_str("\n");

        for (key, value) in self.checksums {
            file_content.push_str(&format!("{}={}\n", key, value));
        }

        std::fs::write(PATH, file_content)?;
        Ok(())
    }

    // Currently Rust always bootstraps from the previous stable release, and in our train model
    // this means that the master branch bootstraps from beta, beta bootstraps from current stable,
    // and stable bootstraps from the previous stable release.
    //
    // On the master branch the compiler version is configured to `beta` whereas if you're looking
    // at the beta or stable channel you'll likely see `1.x.0` as the version, with the previous
    // release's version number.
    fn detect_compiler(&mut self) -> Result<VersionMetadata, Error> {
        let configured_channel = self.config.compiler_dist_channel.trim();
        let channel = if configured_channel.is_empty() {
            match self.channel {
                Channel::Stable | Channel::Beta => {
                    // The 1.XX manifest points to the latest point release of that minor release.
                    format!("{}.{}", self.version[0], self.version[1] - 1)
                }
                Channel::Nightly => "beta".to_string(),
            }
        } else {
            configured_channel.to_string()
        };

        let (manifest, manifest_hash) =
            fetch_manifest(&self.config, &channel, self.compiler_date.as_deref())?;
        self.collect_checksums(&manifest, COMPILER_COMPONENTS)?;
        Ok(VersionMetadata {
            channel_manifest_hash: manifest_hash,
            git_commit_hash: manifest.pkg["rust"]
                .git_commit_hash
                .as_ref()
                .expect("invalid git_commit_hash")
                .into(),
            date: manifest.date,
            version: version_label_for_channel(&channel, &manifest.pkg["rust"].version),
        })
    }

    /// We use a nightly rustfmt to format the source because it solves some bootstrapping issues
    /// with use of new syntax in this repo. For the beta/stable channels rustfmt is not provided,
    /// as we don't want to depend on rustfmt from nightly there.
    fn detect_rustfmt(&mut self) -> Result<Option<VersionMetadata>, Error> {
        let configured_channel = self.config.rustfmt_dist_channel.trim();
        if configured_channel.is_empty() && self.channel != Channel::Nightly {
            return Ok(None);
        }

        let channel = if configured_channel.is_empty() {
            "nightly".to_string()
        } else {
            configured_channel.to_string()
        };

        let (manifest, manifest_hash) =
            fetch_manifest(&self.config, &channel, self.rustfmt_date.as_deref())?;
        self.collect_checksums(&manifest, RUSTFMT_COMPONENTS)?;
        Ok(Some(VersionMetadata {
            channel_manifest_hash: manifest_hash,
            git_commit_hash: manifest.pkg["rust"]
                .git_commit_hash
                .as_ref()
                .expect("invalid git_commit_hash")
                .into(),
            date: manifest.date,
            version: version_label_for_channel(&channel, &manifest.pkg["rust"].version),
        }))
    }

    fn collect_checksums(&mut self, manifest: &Manifest, components: &[&str]) -> Result<(), Error> {
        let prefix = format!("{}/", self.config.dist_server);
        for component in components {
            let pkg = manifest
                .pkg
                .get(*component)
                .ok_or_else(|| anyhow::anyhow!("missing component from manifest: {}", component))?;
            for target in pkg.target.values() {
                for pair in &[(&target.url, &target.hash), (&target.xz_url, &target.xz_hash)] {
                    if let (Some(url), Some(sha256)) = pair {
                        let url = url
                            .strip_prefix(&prefix)
                            .ok_or_else(|| {
                                anyhow::anyhow!("url doesn't start with dist server base: {}", url)
                            })?
                            .to_string();
                        self.checksums.insert(url, sha256.clone());
                    }
                }
            }
        }
        for artifact in manifest.artifacts.values() {
            for targets in artifact.target.values() {
                for target in targets {
                    let url = target
                        .url
                        .strip_prefix(&prefix)
                        .ok_or_else(|| {
                            anyhow::anyhow!(
                                "url doesn't start with dist server base: {}",
                                target.url
                            )
                        })?
                        .to_string();
                    self.checksums.insert(url, target.hash_sha256.clone());
                }
            }
        }
        Ok(())
    }
}

fn main() -> Result<(), Error> {
    let tool = Tool::new(std::env::args().nth(1), std::env::args().nth(2))?;
    tool.update_stage0_file()?;
    Ok(())
}

fn version_label_for_channel(channel: &str, manifest_version: &str) -> String {
    if is_trust_channel(channel) {
        channel.to_string()
    } else {
        match channel {
            "beta" | "nightly" => channel.to_string(),
            _ => manifest_version.split_once(' ').expect("invalid version field").0.to_string(),
        }
    }
}

fn is_trust_channel(channel: &str) -> bool {
    matches!(channel, "trust" | "tRust" | "TRUST")
        || channel.starts_with("trust-")
        || channel.starts_with("tRust-")
        || channel.starts_with("TRUST-")
}

fn fetch_manifest(
    config: &Stage0Config,
    channel: &str,
    date: Option<&str>,
) -> Result<(Manifest, String), Error> {
    let url = if let Some(date) = date {
        format!("{}/dist/{}/channel-rust-{}.toml", config.dist_server, date, channel)
    } else {
        format!("{}/dist/channel-rust-{}.toml", config.dist_server, channel)
    };

    let manifest_bytes = http_get(&url)?;

    let mut sha256 = Sha256::new();
    sha256.update(&manifest_bytes);
    let manifest_hash = hex::encode(sha256.finalize());

    // FIXME: on newer `toml` (>= `0.9.*`), use `toml::from_slice`. For now, we use the most recent
    // `toml` available in-tree which is `0.8.*`, so we have to do an additional dance here.
    let manifest_str = String::from_utf8(manifest_bytes)?;
    let manifest = toml::from_str(&manifest_str)?;
    Ok((manifest, manifest_hash))
}

fn http_get(url: &str) -> Result<Vec<u8>, Error> {
    if let Some(path) = file_url_to_path(url)? {
        return Ok(std::fs::read(path)?);
    }

    let mut data = Vec::new();
    let mut handle = Easy::new();
    handle.fail_on_error(true)?;
    handle.url(url)?;
    {
        let mut transfer = handle.transfer();
        transfer.write_function(|new_data| {
            data.extend_from_slice(new_data);
            Ok(new_data.len())
        })?;
        transfer.perform().context(format!("failed to fetch {url}"))?;
    }
    Ok(data)
}

fn file_url_to_path(url: &str) -> Result<Option<PathBuf>, Error> {
    let Some(raw_path) = url.strip_prefix("file://") else {
        return Ok(None);
    };
    let raw_path = raw_path
        .strip_prefix("localhost/")
        .map(|path| format!("/{path}"))
        .unwrap_or_else(|| raw_path.to_string());
    Ok(Some(PathBuf::from(percent_decode_url_path(&raw_path)?)))
}

fn percent_decode_url_path(path: &str) -> Result<String, Error> {
    let bytes = path.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut idx = 0;
    while idx < bytes.len() {
        if bytes[idx] == b'%' && idx + 2 < bytes.len() {
            if let (Some(high), Some(low)) = (hex_value(bytes[idx + 1]), hex_value(bytes[idx + 2]))
            {
                decoded.push(high << 4 | low);
                idx += 3;
                continue;
            }
        }
        decoded.push(bytes[idx]);
        idx += 1;
    }
    Ok(String::from_utf8(decoded)?)
}

fn hex_value(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        b'A'..=b'F' => Some(byte - b'A' + 10),
        _ => None,
    }
}

#[derive(Debug, PartialEq, Eq)]
enum Channel {
    Stable,
    Beta,
    Nightly,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct Manifest {
    date: String,
    pkg: IndexMap<String, ManifestPackage>,
    #[serde(default)]
    artifacts: IndexMap<String, ManifestArtifact>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct ManifestPackage {
    version: String,
    #[serde(default)]
    git_commit_hash: Option<String>,
    target: IndexMap<String, ManifestTargetPackage>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct ManifestTargetPackage {
    url: Option<String>,
    hash: Option<String>,
    xz_url: Option<String>,
    xz_hash: Option<String>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct ManifestArtifact {
    target: IndexMap<String, Vec<ManifestTargetArtifact>>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
struct ManifestTargetArtifact {
    url: String,
    hash_sha256: String,
}

#[cfg(test)]
mod tests {
    use super::{percent_decode_url_path, version_label_for_channel};

    #[test]
    fn version_label_uses_channel_for_train_channels() {
        assert_eq!(version_label_for_channel("beta", "1.96.0-beta.1 (hash date)"), "beta");
        assert_eq!(version_label_for_channel("nightly", "1.96.0-nightly (hash date)"), "nightly");
    }

    #[test]
    fn version_label_uses_channel_for_trust_channels() {
        assert_eq!(version_label_for_channel("trust", "1.96.0-trust (hash date)"), "trust");
        assert_eq!(
            version_label_for_channel("trust-2026-04-24", "1.96.0-trust (hash date)"),
            "trust-2026-04-24"
        );
        assert_eq!(version_label_for_channel("tRust", "1.96.0-trust (hash date)"), "tRust");
    }

    #[test]
    fn version_label_uses_manifest_version_for_numbered_channels() {
        assert_eq!(version_label_for_channel("1.95", "1.95.1 (hash date)"), "1.95.1");
    }

    #[test]
    fn file_url_paths_are_percent_decoded() {
        assert_eq!(percent_decode_url_path("/tmp/trust%20stage0").unwrap(), "/tmp/trust stage0");
    }
}
