// tRust: split from monolithic archs.rs for maintainability
// Original: File generated by `rustc_codegen_gcc/tools/generate_intrinsics.py`
/// Translate a given LLVM intrinsic name to an equivalent GCC one.
fn map_arch_intrinsic(full_name: &str) -> &'static str {
    let Some(name) = full_name.strip_prefix("llvm.") else {
        unimplemented!("***** unsupported LLVM intrinsic {}", full_name)
    };
    let Some((arch, name)) = name.split_once('.') else {
        unimplemented!("***** unsupported LLVM intrinsic llvm.{}", name)
    };
    let old_arch_res = old_archs(arch, name);
    if let ArchCheckResult::Ok(res) = old_arch_res {
        return res;
    }
    match arch {
        "aarch64" => {
            include!("aarch64.rs");
            aarch64(name, full_name)
        }
        "amdgcn" => {
            include!("amdgcn.rs");
            amdgcn(name, full_name)
        }
        "arm" => {
            include!("arm.rs");
            arm(name, full_name)
        }
        "bpf" => {
            include!("bpf.rs");
            bpf(name, full_name)
        }
        "hexagon" => {
            include!("hexagon.rs");
            hexagon(name, full_name)
        }
        "loongarch" => {
            include!("loongarch.rs");
            loongarch(name, full_name)
        }
        "mips" => {
            include!("mips.rs");
            mips(name, full_name)
        }
        "nvvm" => {
            include!("nvvm.rs");
            nvvm(name, full_name)
        }
        "ppc" => {
            include!("ppc.rs");
            ppc(name, full_name)
        }
        "r600" => {
            include!("r600.rs");
            r600(name, full_name)
        }
        "riscv" => {
            include!("riscv.rs");
            riscv(name, full_name)
        }
        "s390" => {
            include!("s390.rs");
            s390(name, full_name)
        }
        "spv" => {
            include!("spv.rs");
            spv(name, full_name)
        }
        "ve" => {
            include!("ve.rs");
            ve(name, full_name)
        }
        "x86" => {
            include!("x86.rs");
            x86(name, full_name)
        }
        "xcore" => {
            include!("xcore.rs");
            xcore(name, full_name)
        }
        _ => match old_arch_res {
            ArchCheckResult::UnknownIntrinsic => {
                unimplemented!("***** unsupported LLVM intrinsic {full_name}")
            }
            ArchCheckResult::UnknownArch => {
                unimplemented!("***** unsupported LLVM architecture {arch}, intrinsic: {full_name}")
            }
            ArchCheckResult::Ok(_) => unreachable!(),
        },
    }
}
