// trust-testgen: Test suite collection, deduplication, and file writing
//
// Collects generated tests into a module, deduplicates by name, and
// writes the output as a formatted Rust test file.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use trust_types::fx::FxHashSet;
use std::path::Path;
use std::fmt::Write;

use crate::GeneratedTest;

/// Error type for test suite operations.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum TestSuiteError {
    #[error("failed to write test file to {path}: {source}")]
    WriteFile {
        path: String,
        source: std::io::Error,
    },
}

/// A collection of generated tests forming a test module.
#[derive(Debug, Clone)]
pub struct TestSuite {
    /// Module name for the generated test module.
    module_name: String,
    /// Collected tests (insertion order preserved, duplicates removed).
    tests: Vec<GeneratedTest>,
    /// Track test names for deduplication.
    seen_names: FxHashSet<String>,
}

impl TestSuite {
    /// Create a new test suite with the given module name.
    #[must_use]
    pub fn new(module_name: &str) -> Self {
        Self {
            module_name: module_name.to_string(),
            tests: Vec::new(),
            seen_names: FxHashSet::default(),
        }
    }

    /// Add a test to the suite. Duplicate names are silently skipped.
    ///
    /// Returns `true` if the test was added (not a duplicate).
    pub fn add(&mut self, test: GeneratedTest) -> bool {
        if self.seen_names.contains(&test.name) {
            return false;
        }
        self.seen_names.insert(test.name.clone());
        self.tests.push(test);
        true
    }

    /// Add multiple tests, skipping duplicates.
    ///
    /// Returns the number of tests actually added.
    pub fn add_all(&mut self, tests: impl IntoIterator<Item = GeneratedTest>) -> usize {
        tests.into_iter().filter(|t| self.add(t.clone())).count()
    }

    /// Number of unique tests in the suite.
    #[must_use]
    pub fn len(&self) -> usize {
        self.tests.len()
    }

    /// Whether the suite is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.tests.is_empty()
    }

    /// Render the test suite as a complete Rust source file.
    #[must_use]
    pub fn render(&self) -> String {
        let mut out = String::with_capacity(self.tests.len() * 300 + 256);

        let _ = write!(out, 
            "// Auto-generated test suite from tRust verification counterexamples.\n\
             // Module: {}\n\
             //\n\
             // DO NOT EDIT — regenerate with `cargo trust --testgen`.\n\
             //\n\
             // Generated by trust-testgen.\n\n",
            self.module_name,
        );

        let _ = write!(out, "#[cfg(test)]\nmod {} {{\n", self.module_name);

        for (i, test) in self.tests.iter().enumerate() {
            if i > 0 {
                out.push('\n');
            }
            // Indent each line of the test code inside the module.
            for line in test.code.lines() {
                out.push_str("    ");
                out.push_str(line);
                out.push('\n');
            }
        }

        out.push_str("}\n");
        out
    }

    /// Write the test suite to a file.
    pub fn write_to_file(&self, path: &Path) -> Result<(), TestSuiteError> {
        let content = self.render();
        std::fs::write(path, content).map_err(|source| TestSuiteError::WriteFile {
            path: path.display().to_string(),
            source,
        })
    }

    /// Access the collected tests.
    #[must_use]
    pub fn tests(&self) -> &[GeneratedTest] {
        &self.tests
    }

    /// Module name.
    #[must_use]
    pub fn module_name(&self) -> &str {
        &self.module_name
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test(name: &str, code: &str) -> GeneratedTest {
        GeneratedTest {
            name: name.to_string(),
            code: code.to_string(),
            boundary_values: vec![],
        }
    }

    #[test]
    fn test_suite_add_and_len() {
        let mut suite = TestSuite::new("cex_tests");
        assert!(suite.is_empty());

        let added = suite.add(make_test("test_a", "#[test]\nfn test_a() {}"));
        assert!(added);
        assert_eq!(suite.len(), 1);
    }

    #[test]
    fn test_suite_deduplicates_by_name() {
        let mut suite = TestSuite::new("cex_tests");
        suite.add(make_test("test_a", "#[test]\nfn test_a() { /* v1 */ }"));
        let added = suite.add(make_test("test_a", "#[test]\nfn test_a() { /* v2 */ }"));
        assert!(!added);
        assert_eq!(suite.len(), 1);
        // First version should be kept
        assert!(suite.tests()[0].code.contains("v1"));
    }

    #[test]
    fn test_suite_add_all_returns_count() {
        let mut suite = TestSuite::new("tests");
        let tests = vec![
            make_test("test_a", "a"),
            make_test("test_b", "b"),
            make_test("test_a", "a_dup"), // duplicate
        ];
        let count = suite.add_all(tests);
        assert_eq!(count, 2);
        assert_eq!(suite.len(), 2);
    }

    #[test]
    fn test_suite_render_wraps_in_module() {
        let mut suite = TestSuite::new("regression");
        suite.add(make_test(
            "test_overflow",
            "#[test]\nfn test_overflow() {\n    panic!(\"boom\");\n}",
        ));

        let rendered = suite.render();
        assert!(rendered.contains("#[cfg(test)]"));
        assert!(rendered.contains("mod regression {"));
        assert!(rendered.contains("    #[test]"));
        assert!(rendered.contains("    fn test_overflow()"));
        assert!(rendered.contains("}"));
        assert!(rendered.contains("trust-testgen"));
    }

    #[test]
    fn test_suite_render_empty() {
        let suite = TestSuite::new("empty");
        let rendered = suite.render();
        assert!(rendered.contains("mod empty {"));
        assert!(rendered.contains("}"));
        assert!(!rendered.contains("#[test]"));
    }

    #[test]
    fn test_suite_render_multiple_tests() {
        let mut suite = TestSuite::new("multi");
        suite.add(make_test("test_a", "#[test]\nfn test_a() {}"));
        suite.add(make_test("test_b", "#[test]\nfn test_b() {}"));

        let rendered = suite.render();
        assert_eq!(rendered.matches("#[test]").count(), 2);
        assert_eq!(rendered.matches("fn test_").count(), 2);
    }

    #[test]
    fn test_suite_write_to_file_creates_file() {
        let dir = std::env::temp_dir().join("trust_testgen_test");
        let _ = std::fs::create_dir_all(&dir);
        let path = dir.join("generated_tests.rs");

        let mut suite = TestSuite::new("file_tests");
        suite.add(make_test("test_x", "#[test]\nfn test_x() {}"));

        suite.write_to_file(&path).expect("should write file");

        let content = std::fs::read_to_string(&path).expect("should read file");
        assert!(content.contains("test_x"));
        assert!(content.contains("#[cfg(test)]"));

        // Clean up
        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_dir(&dir);
    }

    #[test]
    fn test_suite_write_to_nonexistent_dir_returns_error() {
        let path = Path::new("/nonexistent/dir/tests.rs");
        let suite = TestSuite::new("err");
        let result = suite.write_to_file(path);
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("/nonexistent/dir/tests.rs"));
    }

    #[test]
    fn test_suite_module_name_accessor() {
        let suite = TestSuite::new("my_module");
        assert_eq!(suite.module_name(), "my_module");
    }

    #[test]
    fn test_suite_tests_accessor() {
        let mut suite = TestSuite::new("acc");
        suite.add(make_test("t1", "code1"));
        suite.add(make_test("t2", "code2"));
        assert_eq!(suite.tests().len(), 2);
        assert_eq!(suite.tests()[0].name, "t1");
        assert_eq!(suite.tests()[1].name, "t2");
    }
}
