// trust-vcgen/data_race_tla.rs: TLA+ spec generation for data race VCs
//
// tRust #617: Translates SharedAccess / DataRacePair from the data_race module
// into a TLA+ specification suitable for model checking with a tla2 backend.
// The generated spec models each thread as an action that can read or write a
// shared variable, with a NoDataRace invariant asserting that no two concurrent
// accesses violate the data race definition.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use crate::data_race::{AccessKind, DataRacePair, SharedAccess};

/// tRust #617: Translates data race verification conditions into TLA+ spec text.
///
/// Given a set of shared memory accesses and detected race pairs, produces a
/// TLA+ module that models:
/// - VARIABLES: per-variable state (value + last_writer) and per-thread program counters
/// - Init: all threads at their first access, all variables at initial values
/// - ThreadAction for each thread: a disjunction of possible access steps
/// - Next: disjunction of all thread actions
/// - NoDataRace invariant: no two concurrent accesses violate the race condition
pub struct DataRaceToTla<'a> {
    accesses: &'a [SharedAccess],
    races: &'a [DataRacePair],
    function_name: &'a str,
}

impl<'a> DataRaceToTla<'a> {
    /// Create a new translator.
    #[must_use]
    pub fn new(
        accesses: &'a [SharedAccess],
        races: &'a [DataRacePair],
        function_name: &'a str,
    ) -> Self {
        Self { accesses, races, function_name }
    }

    /// Collect all unique thread IDs from the accesses, sorted for determinism.
    #[must_use]
    fn thread_ids(&self) -> Vec<String> {
        let set: BTreeSet<&str> = self.accesses.iter().map(|a| a.thread_id.as_str()).collect();
        set.into_iter().map(String::from).collect()
    }

    /// Collect all unique shared variable names, sorted for determinism.
    #[must_use]
    fn variable_names(&self) -> Vec<String> {
        let set: BTreeSet<&str> = self.accesses.iter().map(|a| a.variable.as_str()).collect();
        set.into_iter().map(String::from).collect()
    }

    /// Group accesses by thread ID, preserving order within each thread.
    #[must_use]
    fn accesses_by_thread(&self) -> BTreeMap<String, Vec<(usize, &SharedAccess)>> {
        let mut map: BTreeMap<String, Vec<(usize, &SharedAccess)>> = BTreeMap::new();
        for (i, access) in self.accesses.iter().enumerate() {
            map.entry(access.thread_id.clone()).or_default().push((i, access));
        }
        map
    }

    /// Generate TLA+ access kind label for comments/state tracking.
    #[must_use]
    fn access_label(kind: &AccessKind) -> &'static str {
        match kind {
            AccessKind::Read => "Read",
            AccessKind::Write => "Write",
            AccessKind::AtomicRead(_) => "AtomicRead",
            AccessKind::AtomicWrite(_) => "AtomicWrite",
            AccessKind::AtomicRmw(..) => "AtomicRmw",
            AccessKind::Fence(_) => "Fence",
        }
    }

    /// Generate the complete TLA+ module text.
    #[must_use]
    pub fn generate(&self) -> String {
        let module_name = format!("DataRace_{}", sanitize_ident(self.function_name));
        let threads = self.thread_ids();
        let variables = self.variable_names();
        let by_thread = self.accesses_by_thread();

        let mut spec = String::new();

        // Module header
        let dashes = "-".repeat(module_name.len() + 8);
        let _ = writeln!(spec, "---- MODULE {module_name} {dashes}");
        let _ = writeln!(spec, "\\* Data race TLA+ spec for function: {}", self.function_name);
        let _ = writeln!(spec, "\\* Generated by tRust trust-vcgen (Phase 2.3-2.4)");
        let _ = writeln!(spec);

        // VARIABLES
        self.write_variables(&mut spec, &threads, &variables);

        // Init
        self.write_init(&mut spec, &threads, &variables, &by_thread);

        // Thread actions
        for thread in &threads {
            if let Some(thread_accesses) = by_thread.get(thread) {
                self.write_thread_action(&mut spec, thread, thread_accesses, &threads, &variables);
            }
        }

        // Next = disjunction of all thread actions
        self.write_next(&mut spec, &threads);

        // NoDataRace invariant
        self.write_invariant(&mut spec, &threads, &variables);

        // Spec definition
        let _ = writeln!(spec, "Spec == Init /\\ [][Next]_<<{vars}>>",
            vars = self.all_var_list(&threads, &variables),
        );
        let _ = writeln!(spec);

        // Module footer
        let _ = writeln!(spec, "====");

        spec
    }

    /// Write the VARIABLES section.
    fn write_variables(&self, spec: &mut String, threads: &[String], variables: &[String]) {
        let _ = writeln!(spec, "VARIABLES");
        let mut var_list = Vec::new();

        // Per-variable shared state
        for var in variables {
            let safe = sanitize_ident(var);
            var_list.push(format!("  {safe}"));
            var_list.push(format!("  {safe}_writer"));
        }

        // Per-thread program counter
        for thread in threads {
            let safe = sanitize_ident(thread);
            var_list.push(format!("  pc_{safe}"));
        }

        let _ = writeln!(spec, "{}", var_list.join(",\n"));
        let _ = writeln!(spec);
    }

    /// Write the Init predicate.
    fn write_init(
        &self,
        spec: &mut String,
        threads: &[String],
        variables: &[String],
        by_thread: &BTreeMap<String, Vec<(usize, &SharedAccess)>>,
    ) {
        let _ = writeln!(spec, "Init ==");

        // Variables start at initial values
        for var in variables {
            let safe = sanitize_ident(var);
            let _ = writeln!(spec, "  /\\ {safe} = 0");
            let _ = writeln!(spec, "  /\\ {safe}_writer = \"none\"");
        }

        // Each thread starts at step 0 (or "done" if no accesses)
        for thread in threads {
            let safe = sanitize_ident(thread);
            let step_count = by_thread.get(thread).map_or(0, |v| v.len());
            if step_count > 0 {
                let _ = writeln!(spec, "  /\\ pc_{safe} = 0");
            } else {
                let _ = writeln!(spec, "  /\\ pc_{safe} = \"done\"");
            }
        }
        let _ = writeln!(spec);
    }

    /// Write a single thread's action.
    fn write_thread_action(
        &self,
        spec: &mut String,
        thread: &str,
        thread_accesses: &[(usize, &SharedAccess)],
        threads: &[String],
        variables: &[String],
    ) {
        let safe_thread = sanitize_ident(thread);
        let _ = writeln!(spec, "\\* Actions for thread {thread}");
        let _ = writeln!(spec, "ThreadAction_{safe_thread} ==");

        for (step_idx, (_global_idx, access)) in thread_accesses.iter().enumerate() {
            let safe_var = sanitize_ident(&access.variable);
            let label = Self::access_label(&access.access_kind);
            let next_step = if step_idx + 1 < thread_accesses.len() {
                format!("{}", step_idx + 1)
            } else {
                "\"done\"".to_string()
            };

            let _ = writeln!(spec, "  \\/ \\* Step {step_idx}: {label} {}", access.variable);
            let _ = writeln!(spec, "     /\\ pc_{safe_thread} = {step_idx}");

            match &access.access_kind {
                AccessKind::Write | AccessKind::AtomicWrite(_) | AccessKind::AtomicRmw(..) => {
                    // Write: update variable value and record writer
                    let _ = writeln!(spec, "     /\\ {safe_var}' = {safe_var} + 1");
                    let _ = writeln!(spec, "     /\\ {safe_var}_writer' = \"{thread}\"");
                }
                AccessKind::Read | AccessKind::AtomicRead(_) => {
                    // Read: variable unchanged
                    let _ = writeln!(spec, "     /\\ {safe_var}' = {safe_var}");
                    let _ = writeln!(spec, "     /\\ {safe_var}_writer' = {safe_var}_writer");
                }
                AccessKind::Fence(_) => {
                    // Fence: no variable changes
                    let _ = writeln!(spec, "     /\\ UNCHANGED <<{safe_var}, {safe_var}_writer>>");
                }
            }

            let _ = writeln!(spec, "     /\\ pc_{safe_thread}' = {next_step}");

            // UNCHANGED for other threads' pcs and other variables
            let unchanged_pcs: Vec<String> = threads
                .iter()
                .filter(|t| t.as_str() != thread)
                .map(|t| format!("pc_{}", sanitize_ident(t)))
                .collect();
            if !unchanged_pcs.is_empty() {
                let _ = writeln!(spec, "     /\\ UNCHANGED <<{}>>", unchanged_pcs.join(", "));
            }

            let unchanged_vars: Vec<String> = variables
                .iter()
                .filter(|v| v.as_str() != access.variable)
                .flat_map(|v| {
                    let sv = sanitize_ident(v);
                    vec![sv.clone(), format!("{sv}_writer")]
                })
                .collect();
            if !unchanged_vars.is_empty() {
                let _ = writeln!(spec, "     /\\ UNCHANGED <<{}>>", unchanged_vars.join(", "));
            }
        }
        let _ = writeln!(spec);
    }

    /// Write the Next predicate as a disjunction of all thread actions.
    fn write_next(&self, spec: &mut String, threads: &[String]) {
        let _ = writeln!(spec, "Next ==");
        for thread in threads {
            let safe_thread = sanitize_ident(thread);
            let _ = writeln!(spec, "  \\/ ThreadAction_{safe_thread}");
        }
        let _ = writeln!(spec);
    }

    /// Write the NoDataRace invariant.
    ///
    /// For each detected race pair, generates a conjunct asserting that the two
    /// threads cannot be at their respective racing access steps simultaneously.
    fn write_invariant(
        &self,
        spec: &mut String,
        threads: &[String],
        _variables: &[String],
    ) {
        let _ = writeln!(spec, "\\* Invariant: no data race can occur");
        let _ = writeln!(spec, "NoDataRace ==");

        if self.races.is_empty() {
            let _ = writeln!(spec, "  TRUE");
        } else {
            // Map global access index to (thread, step_within_thread)
            let by_thread = self.accesses_by_thread();
            let mut index_to_step: BTreeMap<usize, (String, usize)> = BTreeMap::new();
            for (thread, accesses) in &by_thread {
                for (step_idx, (global_idx, _)) in accesses.iter().enumerate() {
                    index_to_step.insert(*global_idx, (thread.clone(), step_idx));
                }
            }

            for race in self.races {
                let prefix = "  /\\";

                if let (Some((thread_a, step_a)), Some((thread_b, step_b))) =
                    (index_to_step.get(&race.first), index_to_step.get(&race.second))
                {
                    let safe_a = sanitize_ident(thread_a);
                    let safe_b = sanitize_ident(thread_b);
                    let _ = writeln!(
                        spec,
                        "{prefix} \\* Race on {var}: {ta}[{sa}] vs {tb}[{sb}]",
                        var = race.variable,
                        ta = race.thread_a,
                        sa = step_a,
                        tb = race.thread_b,
                        sb = step_b,
                    );
                    let _ = writeln!(
                        spec,
                        "     ~(pc_{safe_a} = {step_a} /\\ pc_{safe_b} = {step_b})",
                    );
                } else {
                    // Fallback: use thread names directly without step mapping
                    let safe_a = sanitize_ident(&race.thread_a);
                    let safe_b = sanitize_ident(&race.thread_b);
                    let _ = writeln!(
                        spec,
                        "{prefix} \\* Race on {var}: {ta} vs {tb}",
                        var = race.variable,
                        ta = race.thread_a,
                        tb = race.thread_b,
                    );
                    let _ = writeln!(
                        spec,
                        "     ~(pc_{safe_a} /= \"done\" /\\ pc_{safe_b} /= \"done\")",
                    );
                }
            }
        }
        let _ = writeln!(spec);

        // Unused parameter suppression — we use threads indirectly via Spec
        let _ = threads;
    }

    /// Build the full variable list string for the Spec definition.
    fn all_var_list(&self, threads: &[String], variables: &[String]) -> String {
        let mut vars = Vec::new();
        for var in variables {
            let safe = sanitize_ident(var);
            vars.push(safe.clone());
            vars.push(format!("{safe}_writer"));
        }
        for thread in threads {
            vars.push(format!("pc_{}", sanitize_ident(thread)));
        }
        vars.join(", ")
    }
}

/// Sanitize an identifier for use in TLA+ (replace non-alphanumeric chars with underscores).
#[must_use]
fn sanitize_ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data_race::{detect_potential_races, AccessKind, MemoryOrdering, SharedAccess};
    use trust_types::SourceSpan;

    fn make_access(
        variable: &str,
        kind: AccessKind,
        thread: &str,
        hb: Vec<usize>,
    ) -> SharedAccess {
        SharedAccess {
            variable: variable.to_string(),
            access_kind: kind,
            thread_id: thread.to_string(),
            happens_before: hb,
            span: SourceSpan::default(),
        }
    }

    #[test]
    fn test_generates_valid_module_header_and_footer() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "test_fn");
        let spec = tla.generate();

        assert!(spec.contains("---- MODULE DataRace_test_fn"), "missing module header");
        assert!(spec.contains("===="), "missing module footer");
    }

    #[test]
    fn test_generates_variables_section() {
        let accesses = vec![
            make_access("counter", AccessKind::Write, "t1", vec![]),
            make_access("counter", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "increment");
        let spec = tla.generate();

        assert!(spec.contains("VARIABLES"), "missing VARIABLES");
        assert!(spec.contains("counter"), "missing shared variable");
        assert!(spec.contains("counter_writer"), "missing writer tracking");
        assert!(spec.contains("pc_t1"), "missing t1 program counter");
        assert!(spec.contains("pc_t2"), "missing t2 program counter");
    }

    #[test]
    fn test_generates_init_predicate() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("Init =="), "missing Init");
        assert!(spec.contains("x = 0"), "missing variable init");
        assert!(spec.contains("x_writer = \"none\""), "missing writer init");
        assert!(spec.contains("pc_t1 = 0"), "missing t1 pc init");
        assert!(spec.contains("pc_t2 = 0"), "missing t2 pc init");
    }

    #[test]
    fn test_generates_thread_actions() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("ThreadAction_t1 =="), "missing t1 action");
        assert!(spec.contains("ThreadAction_t2 =="), "missing t2 action");
    }

    #[test]
    fn test_generates_next_as_disjunction() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("Next =="), "missing Next");
        assert!(spec.contains("ThreadAction_t1"), "Next missing t1");
        assert!(spec.contains("ThreadAction_t2"), "Next missing t2");
    }

    #[test]
    fn test_generates_no_data_race_invariant() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        assert_eq!(races.len(), 1, "expected one race");

        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("NoDataRace =="), "missing invariant");
        assert!(spec.contains("Race on x"), "missing race comment");
        // The invariant should negate the concurrent access condition
        assert!(spec.contains("~("), "missing negation in invariant");
    }

    #[test]
    fn test_generates_spec_definition() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("Spec =="), "missing Spec definition");
        assert!(spec.contains("Init /\\ [][Next]_"), "missing temporal formula");
    }

    #[test]
    fn test_no_races_produces_true_invariant() {
        let accesses = vec![
            make_access("x", AccessKind::Read, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        assert!(races.is_empty());

        let tla = DataRaceToTla::new(&accesses, &races, "safe_fn");
        let spec = tla.generate();

        assert!(spec.contains("NoDataRace =="), "missing invariant");
        assert!(spec.contains("TRUE"), "no-race invariant should be TRUE");
    }

    #[test]
    fn test_multiple_variables_all_present() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("y", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
            make_access("y", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "multi_var");
        let spec = tla.generate();

        assert!(spec.contains("x,"), "missing variable x");
        assert!(spec.contains("x_writer"), "missing x_writer");
        assert!(spec.contains("y"), "missing variable y");
        assert!(spec.contains("y_writer"), "missing y_writer");
    }

    #[test]
    fn test_write_action_updates_variable() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        // The write action should update the variable
        assert!(spec.contains("x' = x + 1"), "write should update variable");
        assert!(spec.contains("x_writer' = \"t1\""), "write should record writer");
    }

    #[test]
    fn test_read_action_preserves_variable() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        // The read action should preserve the variable
        assert!(spec.contains("x' = x\n"), "read should preserve variable");
    }

    #[test]
    fn test_atomic_write_generates_write_action() {
        let accesses = vec![
            make_access("flag", AccessKind::AtomicWrite(MemoryOrdering::Release), "t1", vec![]),
            make_access("flag", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        assert_eq!(races.len(), 1);

        let tla = DataRaceToTla::new(&accesses, &races, "atomic_fn");
        let spec = tla.generate();

        assert!(spec.contains("AtomicWrite"), "should label as AtomicWrite");
        assert!(spec.contains("flag' = flag + 1"), "atomic write should update variable");
    }

    #[test]
    fn test_sanitize_ident_replaces_special_chars() {
        assert_eq!(sanitize_ident("thread-1"), "thread_1");
        assert_eq!(sanitize_ident("my.var"), "my_var");
        assert_eq!(sanitize_ident("a/b"), "a_b");
        assert_eq!(sanitize_ident("normal_id"), "normal_id");
    }

    #[test]
    fn test_thread_done_transition() {
        // Single access per thread: after step 0, pc should go to "done"
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        assert!(spec.contains("pc_t1' = \"done\""), "t1 should transition to done");
        assert!(spec.contains("pc_t2' = \"done\""), "t2 should transition to done");
    }

    #[test]
    fn test_multi_step_thread_advances_pc() {
        let accesses = vec![
            make_access("x", AccessKind::Write, "t1", vec![]),
            make_access("y", AccessKind::Write, "t1", vec![]),
            make_access("x", AccessKind::Read, "t2", vec![]),
        ];
        let races = detect_potential_races(&accesses);
        let tla = DataRaceToTla::new(&accesses, &races, "f");
        let spec = tla.generate();

        // t1 has 2 steps: step 0 -> 1, step 1 -> "done"
        assert!(spec.contains("pc_t1' = 1"), "t1 step 0 should advance to 1");
        assert!(spec.contains("pc_t1' = \"done\""), "t1 step 1 should advance to done");
    }
}
