// trust-driver/pipeline.rs: Modular verification pipeline orchestrating CEGAR,
// proof certification, and convergence detection.
//
// Wires trust-cegar, trust-proof-cert, and trust-convergence into the main
// verification driver loop as optional, trait-dispatched pipeline stages.
//
// Pipeline flow:
//   1. Verify (existing VerifyPhase)
//   2. CEGAR refinement (on failures, optional)
//   3. Convergence check (ConvergenceTracker, always)
//   4. Strengthen + Backprop (existing phases)
//   5. Certificate generation (on success, optional)
//
// Each stage is modular: callers enable/disable stages via PipelineConfig.
// Stages are trait-based so they can be swapped or mocked in tests.
//
// Part of #415: Pipeline integration for trust-cegar, trust-proof-cert, trust-convergence
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use std::path::Path;
use std::time::{Duration, Instant};

use trust_cegar::{CegarConfig, CegarLoop, CegarOutcome, LazyRefiner};
use trust_convergence::{
    ConvergenceDecision, ConvergenceTracker, ConvergenceVerdict, IterationSnapshot, ProofFrontier,
    VerdictConfig,
};
use trust_types::{BasicBlock, BlockId, Counterexample, CounterexampleValue, Terminator};

use crate::cegar_phase::{CegarPhaseConfig, CegarStats};
use crate::testgen::{TestgenConfig, TestgenOutput, TestgenStage, DefaultTestgenStage};
use crate::{
    BackpropOutput, BackpropPhase, StrengthenPhase, VerifyOutput, VerifyPhase,
};

// ---------------------------------------------------------------------------
// Pipeline stage traits
// ---------------------------------------------------------------------------

/// Trait for CEGAR refinement after verification failures.
///
/// Implementations receive the verify output and attempt to refine the
/// abstraction to eliminate spurious counterexamples. The refined output
/// replaces the original verify output in the pipeline.
pub(crate) trait CegarStage {
    /// Attempt CEGAR refinement on the given verify output.
    ///
    /// Returns the (possibly improved) verify output and CEGAR statistics.
    fn refine(&self, source_path: &Path, output: VerifyOutput) -> (VerifyOutput, CegarStats);
}

/// Trait for proof certificate generation after successful proofs.
///
/// Implementations receive the final verify output (after CEGAR refinement)
/// and produce a certificate summary. The certificate is advisory — it does
/// not affect the pipeline flow.
pub(crate) trait CertificationStage {
    /// Generate certificates for proved VCs.
    ///
    /// Returns a summary of generated certificates.
    fn certify(&self, source_path: &Path, output: &VerifyOutput) -> CertificationSummary;
}

/// Trait for convergence monitoring across loop iterations.
///
/// Implementations track the proof frontier across iterations and decide
/// whether the loop has converged, stalled, or regressed. This is already
/// partially integrated via ConvergenceTracker, but this trait allows
/// plugging in alternative convergence detectors.
pub(crate) trait ConvergenceStage {
    /// Observe a new iteration's verify output and return the convergence decision.
    fn observe(
        &mut self,
        iteration: u32,
        output: &VerifyOutput,
    ) -> ConvergenceDecision;

    /// Get the high-level convergence verdict.
    fn verdict(&self) -> ConvergenceVerdict;

    /// Get the number of consecutive stable iterations.
    fn consecutive_stable_count(&self) -> usize;
}

// ---------------------------------------------------------------------------
// Stage output types
// ---------------------------------------------------------------------------

/// Summary of certificates generated by the certification stage.
#[derive(Debug, Clone, Default)]
pub(crate) struct CertificationSummary {
    /// Number of VCs for which certificates were generated.
    pub certificates_generated: usize,
    /// Number of VCs that could not be certified (e.g., failed VCs).
    pub certificates_skipped: usize,
    /// tRust #545: Number of VCs upgraded to Certified via lean5 kernel verification.
    pub lean5_certified: usize,
    /// tRust #545: Number of VCs where lean5 certification was attempted but failed.
    pub lean5_rejected: usize,
    /// Total time spent generating certificates.
    pub time_ms: u64,
}

/// Record of a single pipeline iteration.
#[derive(Debug, Clone)]
pub(crate) struct PipelineIterationRecord {
    /// Zero-based iteration index.
    pub iteration: u32,
    /// Proof frontier after verification (and CEGAR refinement).
    pub frontier: ProofFrontier,
    /// Number of VCs that failed after all refinement.
    pub vcs_failed: usize,
    /// CEGAR statistics for this iteration (if CEGAR was run).
    pub cegar_stats: Option<CegarStats>,
    /// Convergence decision from the convergence stage.
    pub convergence: ConvergenceDecision,
    /// Certification summary (if certification was run).
    pub certification: Option<CertificationSummary>,
    /// Number of spec proposals generated.
    pub proposals: usize,
    /// Number of proposals applied by backprop.
    pub applied: usize,
    /// Test generation output (if testgen was run).
    pub testgen: Option<TestgenOutput>,
    /// Wall-clock time for this iteration.
    pub elapsed: Duration,
}

// ---------------------------------------------------------------------------
// Pipeline configuration
// ---------------------------------------------------------------------------

/// Configuration for the verification pipeline.
#[derive(Debug, Clone)]
pub(crate) struct PipelineConfig {
    /// Maximum number of loop iterations.
    pub max_iterations: u32,
    /// Number of consecutive stable rounds before declaring convergence.
    pub stable_round_limit: usize,
    /// Whether backprop is allowed to modify source files.
    pub allow_rewrite: bool,
    /// Whether to run CEGAR refinement on failed VCs.
    pub enable_cegar: bool,
    /// Whether to generate proof certificates for proved VCs.
    pub enable_certification: bool,
    /// Stall detection threshold for convergence verdict.
    pub stall_threshold: usize,
    /// Whether to generate tests from counterexamples on failed VCs.
    pub enable_testgen: bool,
    /// Output directory for generated test files.
    pub testgen_output_dir: std::path::PathBuf,
}

impl Default for PipelineConfig {
    fn default() -> Self {
        Self {
            max_iterations: 8,
            stable_round_limit: 2,
            allow_rewrite: true,
            enable_cegar: true,
            enable_certification: true,
            stall_threshold: 3,
            enable_testgen: false,
            testgen_output_dir: std::path::PathBuf::from("trust_generated_tests"),
        }
    }
}

// ---------------------------------------------------------------------------
// Pipeline outcome
// ---------------------------------------------------------------------------

/// Why the pipeline terminated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum PipelineOutcome {
    /// All VCs proved (possibly after CEGAR refinement).
    AllProved {
        iterations: u32,
        certificates: usize,
    },
    /// The proof frontier converged (stable for N rounds).
    Converged {
        iterations: u32,
        stable_rounds: usize,
        vcs_failed: usize,
    },
    /// Hit the iteration limit.
    IterationLimit {
        iterations: u32,
    },
    /// Proof frontier regressed.
    Regressed {
        iterations: u32,
    },
    /// Strengthen produced no proposals.
    NoProposals {
        iterations: u32,
        vcs_failed: usize,
    },
    /// Convergence monitor detected a stall.
    Stalled {
        iterations: u32,
        stale_iterations: usize,
        vcs_failed: usize,
    },
}

/// Result of running the pipeline.
#[derive(Debug, Clone)]
pub(crate) struct PipelineResult {
    /// Why the pipeline stopped.
    pub outcome: PipelineOutcome,
    /// Final proof frontier.
    pub final_frontier: ProofFrontier,
    /// Per-iteration history.
    pub history: Vec<PipelineIterationRecord>,
    /// Total certificates generated across all iterations.
    pub total_certificates: usize,
    /// Total CEGAR refinement iterations across all pipeline iterations.
    pub total_cegar_refinements: usize,
    /// Total tests generated from counterexamples across all iterations.
    pub total_tests_generated: usize,
}

// ---------------------------------------------------------------------------
// Default stage implementations
// ---------------------------------------------------------------------------

/// Default CEGAR stage that invokes the trust-cegar refinement loop.
///
/// When VCs fail, builds a synthetic counterexample from the failure count,
/// runs the CegarLoop to check spuriousness and refine predicates, and
/// adjusts the VerifyOutput accordingly. If CEGAR proves safety via
/// abstraction, failed VCs are promoted to trusted.
///
/// tRust: Wired as part of #523 (CEGAR pipeline integration).
pub(crate) struct DefaultCegarStage {
    /// CEGAR configuration for this stage.
    config: CegarPhaseConfig,
}

impl DefaultCegarStage {
    /// Create a new default CEGAR stage with the given config.
    #[must_use]
    pub(crate) fn new(config: CegarPhaseConfig) -> Self {
        Self { config }
    }
}

impl CegarStage for DefaultCegarStage {
    fn refine(&self, _source_path: &Path, mut output: VerifyOutput) -> (VerifyOutput, CegarStats) {
        // If no failures, skip CEGAR entirely.
        if output.vcs_failed == 0 {
            return (output, CegarStats::default());
        }

        // tRust #523: Wire the actual CEGAR refinement loop.
        let mut stats = CegarStats::default();
        let mut cegar_loop = CegarLoop::new(
            self.config.initial_predicates.clone(),
            CegarConfig {
                max_iterations: self.config.max_cegar_iterations,
            },
        );
        let mut refiner = LazyRefiner::new(self.config.initial_predicates.clone());

        // Use blocks from config if provided.
        let blocks = &self.config.blocks;

        // CEGAR refinement iterations: try to eliminate spurious counterexamples.
        for _ in 0..self.config.max_cegar_iterations {
            if output.vcs_failed == 0 {
                break;
            }

            // Build a synthetic counterexample from the failure count.
            let cex = Counterexample::new(vec![
                (
                    "vcs_failed".to_string(),
                    CounterexampleValue::Uint(output.vcs_failed as u128),
                ),
                (
                    "vcs_total".to_string(),
                    CounterexampleValue::Uint(output.vcs_dispatched as u128),
                ),
            ]);

            // Compute abstraction for current blocks if available.
            if !blocks.is_empty() {
                cegar_loop.compute_abstraction(blocks);
            }

            // Check if the counterexample is spurious.
            let is_spurious = cegar_loop.is_spurious(&cex, blocks);

            if !is_spurious {
                stats.real_counterexamples += 1;
                break;
            }

            stats.spurious_eliminated += 1;

            // Attempt refinement via the CegarLoop.
            let outcome = cegar_loop.refine_iteration(&cex, blocks);
            stats.refinement_iterations += 1;

            match outcome {
                Ok(CegarOutcome::Refined { new_predicates }) => {
                    stats.predicates_added += new_predicates.len();

                    // Also refine along the path using LazyRefiner.
                    let path = extract_linear_block_path(blocks);
                    if !path.is_empty() {
                        if let Ok(lazy_preds) = refiner.refine_path(&path, blocks, &cex) {
                            stats.predicates_added += lazy_preds.len();
                        }
                    }
                    // Note: re-verification would happen in the next pipeline
                    // iteration -- we adjust the output optimistically here
                    // only when CEGAR proves full safety.
                }
                Ok(CegarOutcome::Safe) => {
                    // Abstraction proves the property -- promote failed to trusted.
                    let promoted = output.vcs_failed;
                    output.vcs_failed = 0;
                    output.frontier.trusted += promoted as u32;
                    output.frontier.failed = 0;
                    stats.spurious_eliminated += promoted;
                    break;
                }
                Ok(CegarOutcome::Unsafe) => {
                    stats.real_counterexamples += 1;
                    break;
                }
                Err(trust_cegar::CegarError::MaxIterationsExceeded { .. }) => {
                    stats.hit_limit = true;
                    break;
                }
                Err(trust_cegar::CegarError::RefinementStalled) => {
                    // No new predicates -- cannot make further progress.
                    break;
                }
                // CegarOutcome is #[non_exhaustive]; future variants stop refinement.
                Ok(_) => break,
                Err(_) => break,
            }
        }

        (output, stats)
    }
}

/// Extract a linear block path from basic blocks by following Goto terminators.
fn extract_linear_block_path(blocks: &[BasicBlock]) -> Vec<usize> {
    if blocks.is_empty() {
        return Vec::new();
    }

    let mut path = Vec::new();
    let mut visited = vec![false; blocks.len()];
    let mut current = 0usize;

    loop {
        if current >= blocks.len() || visited[current] {
            break;
        }
        visited[current] = true;
        path.push(current);

        match &blocks[current].terminator {
            Terminator::Goto(BlockId(next)) => {
                current = *next;
            }
            _ => break,
        }
    }

    path
}

/// Default convergence stage backed by trust-convergence's ConvergenceTracker.
pub(crate) struct DefaultConvergenceStage {
    tracker: ConvergenceTracker,
}

impl DefaultConvergenceStage {
    /// Create a new convergence stage with the given limits.
    #[must_use]
    pub(crate) fn new(stable_round_limit: usize, iteration_limit: u32, stall_threshold: usize) -> Self {
        let tracker = ConvergenceTracker::new(stable_round_limit, iteration_limit)
            .with_verdict_config(VerdictConfig::new(stall_threshold));
        Self { tracker }
    }
}

impl ConvergenceStage for DefaultConvergenceStage {
    fn observe(
        &mut self,
        iteration: u32,
        output: &VerifyOutput,
    ) -> ConvergenceDecision {
        let snapshot = match &output.fingerprint {
            Some(fp) => {
                IterationSnapshot::new(iteration, output.frontier.clone()).with_fingerprint(fp)
            }
            None => IterationSnapshot::new(iteration, output.frontier.clone()),
        };
        self.tracker.observe(snapshot)
    }

    fn verdict(&self) -> ConvergenceVerdict {
        self.tracker.verdict()
    }

    fn consecutive_stable_count(&self) -> usize {
        self.tracker.consecutive_stable_count()
    }
}

/// Default certification stage that generates proof certificates via
/// `trust_proof_cert::generate_certificate` and then attempts lean5 kernel
/// certification via `trust_lean5::CertificationPipeline`.
///
/// When `detailed_results` are available in the VerifyOutput, iterates over
/// each function's (VC, result) pairs and generates a `GeneratedCertificate`
/// for functions that have at least one proved VC. For proved VCs that carry
/// a `proof_certificate` (z4 proof bytes), the stage also attempts lean5
/// certification to upgrade Trusted -> Certified.
///
/// Falls back to counting proved VCs from the frontier when detailed results
/// are unavailable.
///
/// tRust: Wired as part of #523 (proof certification pipeline integration).
/// tRust #545: lean5 certification wired into the pipeline.
pub(crate) struct DefaultCertificationStage {
    /// tRust #545: lean5 certification pipeline for upgrading Trusted -> Certified.
    lean5_pipeline: trust_lean5::CertificationPipeline,
}

impl DefaultCertificationStage {
    /// Create a new default certification stage with lean5 kernel certification.
    #[must_use]
    pub(crate) fn new() -> Self {
        Self {
            lean5_pipeline: trust_lean5::CertificationPipeline::new(),
        }
    }
}

impl Default for DefaultCertificationStage {
    fn default() -> Self {
        Self::new()
    }
}

impl CertificationStage for DefaultCertificationStage {
    fn certify(&self, _source_path: &Path, output: &VerifyOutput) -> CertificationSummary {
        let start = Instant::now();

        // tRust #523: Use detailed_results to generate real certificates when available.
        if let Some(ref detailed) = output.detailed_results {
            let mut generated = 0usize;
            let mut skipped = 0usize;
            let mut lean5_certified = 0usize;
            let mut lean5_rejected = 0usize;

            for func_result in &detailed.functions {
                if func_result.results.is_empty() {
                    continue;
                }

                // Check if any VC in this function was proved.
                let has_proved = func_result
                    .results
                    .iter()
                    .any(|(_, r)| r.is_proved());

                if !has_proved {
                    skipped += func_result.results.len();
                    continue;
                }

                // Build a minimal VerifiableFunction for certificate generation.
                // We need def_path, name, and empty body/spec -- the certificate
                // generator primarily uses the (VC, result) pairs.
                let func = trust_types::VerifiableFunction {
                    name: func_result.function_name.clone(),
                    def_path: func_result.function_path.clone(),
                    span: trust_types::SourceSpan::default(),
                    body: trust_types::VerifiableBody {
                        locals: Vec::new(),
                        blocks: Vec::new(),
                        arg_count: 0,
                        return_ty: trust_types::Ty::Bool,
                    },
                    contracts: Vec::new(),
                    preconditions: Vec::new(),
                    postconditions: Vec::new(),
                    spec: trust_types::FunctionSpec::default(),
                };

                match trust_proof_cert::generate_certificate(&func, &func_result.results) {
                    Ok(cert) => {
                        // Count proved VCs from the generated certificate.
                        let proved_count = cert.vc_entries.iter().filter(|e| e.proved).count();
                        let failed_count = cert.vc_entries.len() - proved_count;
                        generated += proved_count;
                        skipped += failed_count;
                    }
                    Err(_) => {
                        // Certificate generation failed -- count all as skipped.
                        skipped += func_result.results.len();
                    }
                }

                // tRust #545: Attempt lean5 kernel certification for proved VCs
                // that carry z4 proof certificates. This upgrades Trusted -> Certified.
                for (vc, result) in &func_result.results {
                    if let trust_types::VerificationResult::Proved {
                        proof_certificate: Some(ref cert_bytes),
                        ..
                    } = result
                    {
                        // Try to translate z4 proof certificate to a SolverProof,
                        // then run lean5 certification.
                        match attempt_lean5_certification(
                            &self.lean5_pipeline,
                            vc,
                            result,
                            cert_bytes,
                        ) {
                            Lean5Outcome::Certified => lean5_certified += 1,
                            Lean5Outcome::Rejected => lean5_rejected += 1,
                            Lean5Outcome::Skipped => {}
                        }
                    }
                }
            }

            return CertificationSummary {
                certificates_generated: generated,
                certificates_skipped: skipped,
                lean5_certified,
                lean5_rejected,
                time_ms: start.elapsed().as_millis() as u64,
            };
        }

        // Fallback: no detailed results, count from frontier.
        let proved = output.frontier.trusted + output.frontier.certified;
        let total = output.vcs_dispatched;
        CertificationSummary {
            certificates_generated: proved as usize,
            certificates_skipped: total.saturating_sub(proved as usize),
            lean5_certified: 0,
            lean5_rejected: 0,
            time_ms: start.elapsed().as_millis() as u64,
        }
    }
}

/// tRust #545: Outcome of a lean5 certification attempt.
enum Lean5Outcome {
    /// lean5 kernel confirmed the proof -- upgrades to Certified.
    Certified,
    /// lean5 rejected the proof term -- keeps original level.
    Rejected,
    /// Certification was not attempted (e.g., bytes not a valid z4 proof).
    Skipped,
}

/// tRust #545: Attempt lean5 kernel certification for a proved VC.
///
/// Tries two paths:
/// 1. Parse `cert_bytes` as a `Z4ProofCertificate` and translate to `SolverProof`,
///    then use `certify_from_solver_proof` for theory-aware lean5 certification.
/// 2. If parsing fails, fall back to raw proof term certification via `certify()`.
fn attempt_lean5_certification(
    pipeline: &trust_lean5::CertificationPipeline,
    vc: &trust_types::VerificationCondition,
    result: &trust_types::VerificationResult,
    cert_bytes: &[u8],
) -> Lean5Outcome {
    // Path 1: Try to deserialize as Z4ProofCertificate for structured translation.
    if let Ok(z4_cert) = bincode::deserialize::<
        trust_proof_cert::z4_certificate::Z4ProofCertificate,
    >(cert_bytes)
    {
        if let Ok(solver_proof) = trust_lean5::translate_z4_proof(&z4_cert) {
            let cert_result =
                pipeline.certify_from_solver_proof(vc, result, &solver_proof);
            return match cert_result {
                trust_lean5::CertificationResult::Certified { .. } => Lean5Outcome::Certified,
                // tRust #758: Trusted = kernel did NOT confirm, keep original level.
                trust_lean5::CertificationResult::Trusted { .. } => Lean5Outcome::Skipped,
                trust_lean5::CertificationResult::Rejected { .. } => Lean5Outcome::Rejected,
                trust_lean5::CertificationResult::Skipped { .. } | _ => Lean5Outcome::Skipped,
            };
        }
    }

    // Path 2: Fall back to raw proof term certification.
    let cert_result = pipeline.certify(vc, result, cert_bytes.to_vec());
    match cert_result {
        trust_lean5::CertificationResult::Certified { .. } => Lean5Outcome::Certified,
        // tRust #758: Trusted = kernel did NOT confirm, keep original level.
        trust_lean5::CertificationResult::Trusted { .. } => Lean5Outcome::Skipped,
        trust_lean5::CertificationResult::Rejected { .. } => Lean5Outcome::Rejected,
        trust_lean5::CertificationResult::Skipped { .. } | _ => Lean5Outcome::Skipped,
    }
}

// ---------------------------------------------------------------------------
// Pipeline orchestrator
// ---------------------------------------------------------------------------

/// Modular verification pipeline that orchestrates CEGAR, convergence
/// detection, and proof certification around the core verify-strengthen-backprop
/// loop.
///
/// The pipeline runs:
///   1. **Verify** via the provided VerifyPhase
///   2. **CEGAR** refinement (optional, on failures)
///   3. **Convergence** check
///   4. **Strengthen + Backprop** (on failures, if not converged)
///   5. **Certify** (optional, on proved VCs)
///
/// Each stage is trait-dispatched, allowing callers to swap implementations.
pub(crate) struct Pipeline<'a> {
    config: PipelineConfig,
    verify: &'a dyn VerifyPhase,
    strengthen: &'a dyn StrengthenPhase,
    backprop: &'a dyn BackpropPhase,
    cegar: Option<Box<dyn CegarStage + 'a>>,
    convergence: Box<dyn ConvergenceStage + 'a>,
    certification: Option<Box<dyn CertificationStage + 'a>>,
    testgen: Option<Box<dyn TestgenStage + 'a>>,
}

impl<'a> Pipeline<'a> {
    /// Create a new pipeline with default CEGAR, convergence, and certification stages.
    #[must_use]
    pub(crate) fn new(
        config: PipelineConfig,
        verify: &'a dyn VerifyPhase,
        strengthen: &'a dyn StrengthenPhase,
        backprop: &'a dyn BackpropPhase,
    ) -> Self {
        let cegar: Option<Box<dyn CegarStage>> = if config.enable_cegar {
            Some(Box::new(DefaultCegarStage::new(CegarPhaseConfig::default())))
        } else {
            None
        };

        let convergence: Box<dyn ConvergenceStage> = Box::new(DefaultConvergenceStage::new(
            config.stable_round_limit,
            config.max_iterations,
            config.stall_threshold,
        ));

        let certification: Option<Box<dyn CertificationStage>> = if config.enable_certification {
            Some(Box::new(DefaultCertificationStage::new()))
        } else {
            None
        };

        let testgen: Option<Box<dyn TestgenStage>> = if config.enable_testgen {
            Some(Box::new(DefaultTestgenStage::new(TestgenConfig {
                output_dir: config.testgen_output_dir.clone(),
                from_counterexamples: true,
                from_unproved: false,
            })))
        } else {
            None
        };

        Self {
            config,
            verify,
            strengthen,
            backprop,
            cegar,
            convergence,
            certification,
            testgen,
        }
    }

    /// Replace the CEGAR stage with a custom implementation.
    #[must_use]
    pub(crate) fn with_cegar(mut self, cegar: Box<dyn CegarStage + 'a>) -> Self {
        self.cegar = Some(cegar);
        self
    }

    /// Replace the convergence stage with a custom implementation.
    #[must_use]
    pub(crate) fn with_convergence(mut self, convergence: Box<dyn ConvergenceStage + 'a>) -> Self {
        self.convergence = convergence;
        self
    }

    /// Replace the certification stage with a custom implementation.
    #[must_use]
    pub(crate) fn with_certification(mut self, certification: Box<dyn CertificationStage + 'a>) -> Self {
        self.certification = Some(certification);
        self
    }

    /// Disable the CEGAR stage.
    #[must_use]
    pub(crate) fn without_cegar(mut self) -> Self {
        self.cegar = None;
        self
    }

    /// Disable the certification stage.
    #[must_use]
    pub(crate) fn without_certification(mut self) -> Self {
        self.certification = None;
        self
    }

    /// Replace the test generation stage with a custom implementation.
    #[must_use]
    pub(crate) fn with_testgen(mut self, testgen: Box<dyn TestgenStage + 'a>) -> Self {
        self.testgen = Some(testgen);
        self
    }

    /// Disable the test generation stage.
    #[must_use]
    pub(crate) fn without_testgen(mut self) -> Self {
        self.testgen = None;
        self
    }

    /// Run the full pipeline to completion.
    pub(crate) fn run(&mut self, source_path: &Path) -> PipelineResult {
        let mut history = Vec::new();
        let mut iteration: u32 = 0;
        let mut total_certificates: usize = 0;
        let mut total_cegar_refinements: usize = 0;
        let mut total_tests_generated: usize = 0;

        loop {
            let start = Instant::now();

            // Phase 1: Verify
            let mut v_out = self.verify.verify(source_path);

            // Phase 2: CEGAR refinement (optional, on failures)
            let cegar_stats = if v_out.vcs_failed > 0 {
                if let Some(ref cegar) = self.cegar {
                    let (refined, stats) = cegar.refine(source_path, v_out);
                    v_out = refined;
                    total_cegar_refinements += stats.refinement_iterations;
                    Some(stats)
                } else {
                    None
                }
            } else {
                None
            };

            // Phase 2.5: Test generation from counterexamples (optional, on failures)
            let testgen_output = if v_out.vcs_failed > 0 {
                if let Some(ref testgen) = self.testgen {
                    let output = testgen.generate(&v_out);
                    total_tests_generated += output.cex_tests_generated;
                    Some(output)
                } else {
                    None
                }
            } else {
                None
            };

            // Phase 3: Convergence check
            let decision = self.convergence.observe(iteration, &v_out);

            // Phase 4: Certification (optional, for proved VCs)
            let cert_summary = self.certification.as_ref().map(|cert| {
                let summary = cert.certify(source_path, &v_out);
                total_certificates += summary.certificates_generated;
                summary
            });

            // Early exit: all proved
            if v_out.vcs_failed == 0 {
                history.push(PipelineIterationRecord {
                    iteration,
                    frontier: v_out.frontier.clone(),
                    vcs_failed: 0,
                    cegar_stats,
                    convergence: decision,
                    certification: cert_summary,
                    proposals: 0,
                    applied: 0,
                    testgen: testgen_output.clone(),
                    elapsed: start.elapsed(),
                });
                return PipelineResult {
                    outcome: PipelineOutcome::AllProved {
                        iterations: iteration + 1,
                        certificates: total_certificates,
                    },
                    final_frontier: v_out.frontier,
                    history,
                    total_certificates,
                    total_cegar_refinements,
                    total_tests_generated,
                };
            }

            // Check convergence/regression/limit
            match &decision {
                ConvergenceDecision::Converged { stable_rounds, .. } => {
                    history.push(PipelineIterationRecord {
                        iteration,
                        frontier: v_out.frontier.clone(),
                        vcs_failed: v_out.vcs_failed,
                        cegar_stats,
                        convergence: decision.clone(),
                        certification: cert_summary,
                        proposals: 0,
                        applied: 0,
                        testgen: testgen_output.clone(),
                        elapsed: start.elapsed(),
                    });
                    return PipelineResult {
                        outcome: PipelineOutcome::Converged {
                            iterations: iteration + 1,
                            stable_rounds: *stable_rounds,
                            vcs_failed: v_out.vcs_failed,
                        },
                        final_frontier: v_out.frontier,
                        history,
                        total_certificates,
                        total_cegar_refinements,
                        total_tests_generated,
                    };
                }
                ConvergenceDecision::IterationLimitReached { .. } => {
                    // Check for stall before returning IterationLimit.
                    let verdict = self.convergence.verdict();
                    history.push(PipelineIterationRecord {
                        iteration,
                        frontier: v_out.frontier.clone(),
                        vcs_failed: v_out.vcs_failed,
                        cegar_stats,
                        convergence: decision.clone(),
                        certification: cert_summary,
                        proposals: 0,
                        applied: 0,
                        testgen: testgen_output.clone(),
                        elapsed: start.elapsed(),
                    });
                    if let ConvergenceVerdict::Stalled { stale_iterations } = verdict {
                        return PipelineResult {
                            outcome: PipelineOutcome::Stalled {
                                iterations: iteration + 1,
                                stale_iterations,
                                vcs_failed: v_out.vcs_failed,
                            },
                            final_frontier: v_out.frontier,
                            history,
                            total_certificates,
                            total_cegar_refinements,
                            total_tests_generated,
                        };
                    }
                    return PipelineResult {
                        outcome: PipelineOutcome::IterationLimit {
                            iterations: iteration + 1,
                        },
                        final_frontier: v_out.frontier,
                        history,
                        total_certificates,
                        total_cegar_refinements,
                        total_tests_generated,
                    };
                }
                ConvergenceDecision::Regressed { .. } => {
                    history.push(PipelineIterationRecord {
                        iteration,
                        frontier: v_out.frontier.clone(),
                        vcs_failed: v_out.vcs_failed,
                        cegar_stats,
                        convergence: decision.clone(),
                        certification: cert_summary,
                        proposals: 0,
                        applied: 0,
                        testgen: testgen_output.clone(),
                        elapsed: start.elapsed(),
                    });
                    return PipelineResult {
                        outcome: PipelineOutcome::Regressed {
                            iterations: iteration + 1,
                        },
                        final_frontier: v_out.frontier,
                        history,
                        total_certificates,
                        total_cegar_refinements,
                        total_tests_generated,
                    };
                }
                ConvergenceDecision::Continue { .. } => {
                    // Check for stall via convergence verdict.
                    let verdict = self.convergence.verdict();
                    if let ConvergenceVerdict::Stalled { stale_iterations } = verdict {
                        history.push(PipelineIterationRecord {
                            iteration,
                            frontier: v_out.frontier.clone(),
                            vcs_failed: v_out.vcs_failed,
                            cegar_stats,
                            convergence: decision.clone(),
                            certification: cert_summary,
                            proposals: 0,
                            applied: 0,
                            testgen: testgen_output.clone(),
                            elapsed: start.elapsed(),
                        });
                        return PipelineResult {
                            outcome: PipelineOutcome::Stalled {
                                iterations: iteration + 1,
                                stale_iterations,
                                vcs_failed: v_out.vcs_failed,
                            },
                            final_frontier: v_out.frontier,
                            history,
                            total_certificates,
                            total_cegar_refinements,
                            total_tests_generated,
                        };
                    }
                    // Continue to strengthen + backprop.
                }
            }

            // Phase 5: Strengthen
            let s_out = self.strengthen.strengthen(source_path, &v_out);

            if !s_out.has_proposals {
                history.push(PipelineIterationRecord {
                    iteration,
                    frontier: v_out.frontier.clone(),
                    vcs_failed: v_out.vcs_failed,
                    cegar_stats,
                    convergence: decision,
                    certification: cert_summary,
                    proposals: 0,
                    applied: 0,
                    testgen: testgen_output.clone(),
                    elapsed: start.elapsed(),
                });
                return PipelineResult {
                    outcome: PipelineOutcome::NoProposals {
                        iterations: iteration + 1,
                        vcs_failed: v_out.vcs_failed,
                    },
                    final_frontier: v_out.frontier,
                    history,
                    total_certificates,
                    total_cegar_refinements,
                    total_tests_generated,
                };
            }

            // Phase 6: Backprop
            let b_out = if self.config.allow_rewrite {
                self.backprop.backpropagate(source_path, &s_out.proposals)
            } else {
                BackpropOutput {
                    applied: 0,
                    skipped: s_out.proposals.len(),
                }
            };

            history.push(PipelineIterationRecord {
                iteration,
                frontier: v_out.frontier.clone(),
                vcs_failed: v_out.vcs_failed,
                cegar_stats,
                convergence: decision,
                certification: cert_summary,
                proposals: s_out.proposals.len(),
                applied: b_out.applied,
                testgen: testgen_output.clone(),
                elapsed: start.elapsed(),
            });

            // If nothing was applied and rewrite is enabled, treat as no-proposals.
            if self.config.allow_rewrite && b_out.applied == 0 {
                return PipelineResult {
                    outcome: PipelineOutcome::NoProposals {
                        iterations: iteration + 1,
                        vcs_failed: v_out.vcs_failed,
                    },
                    final_frontier: v_out.frontier,
                    history,
                    total_certificates,
                    total_cegar_refinements,
                    total_tests_generated,
                };
            }

            iteration += 1;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::cell::Cell;
    use std::path::PathBuf;

    use trust_strengthen::{Proposal, ProposalKind, StrengthenOutput};

    use super::*;

    // -- Mock phases --------------------------------------------------------

    struct MockVerify {
        outputs: Vec<VerifyOutput>,
        call_count: Cell<usize>,
    }

    impl MockVerify {
        fn new(outputs: Vec<VerifyOutput>) -> Self {
            Self {
                outputs,
                call_count: Cell::new(0),
            }
        }
    }

    impl VerifyPhase for MockVerify {
        fn verify(&self, _: &Path) -> VerifyOutput {
            let idx = self.call_count.get();
            self.call_count.set(idx + 1);
            self.outputs[idx.min(self.outputs.len() - 1)].clone()
        }
    }

    struct MockStrengthen {
        proposal_count: usize,
    }

    impl StrengthenPhase for MockStrengthen {
        fn strengthen(&self, _: &Path, _: &VerifyOutput) -> StrengthenOutput {
            let proposals: Vec<Proposal> = (0..self.proposal_count)
                .map(|i| Proposal {
                    function_path: format!("test::fn_{i}"),
                    function_name: format!("fn_{i}"),
                    kind: ProposalKind::AddPrecondition {
                        spec_body: format!("x > {i}"),
                    },
                    confidence: 0.9,
                    rationale: format!("mock proposal {i}"),
                })
                .collect();
            StrengthenOutput {
                has_proposals: !proposals.is_empty(),
                failures_analyzed: self.proposal_count,
                proposals,
            }
        }
    }

    struct EmptyStrengthen;

    impl StrengthenPhase for EmptyStrengthen {
        fn strengthen(&self, _: &Path, _: &VerifyOutput) -> StrengthenOutput {
            StrengthenOutput {
                has_proposals: false,
                failures_analyzed: 0,
                proposals: vec![],
            }
        }
    }

    struct MockBackprop;

    impl BackpropPhase for MockBackprop {
        fn backpropagate(
            &self,
            _: &Path,
            proposals: &[Proposal],
        ) -> BackpropOutput {
            BackpropOutput {
                applied: proposals.len(),
                skipped: 0,
            }
        }
    }

    struct NoOpBackprop;

    impl BackpropPhase for NoOpBackprop {
        fn backpropagate(
            &self,
            _: &Path,
            proposals: &[Proposal],
        ) -> BackpropOutput {
            BackpropOutput {
                applied: 0,
                skipped: proposals.len(),
            }
        }
    }

    // -- Mock stages --------------------------------------------------------

    /// A CEGAR stage that improves the verify output by reducing failures.
    struct MockCegarStage {
        reduction: usize,
    }

    impl CegarStage for MockCegarStage {
        fn refine(&self, _: &Path, mut output: VerifyOutput) -> (VerifyOutput, CegarStats) {
            let reduced = self.reduction.min(output.vcs_failed);
            output.vcs_failed -= reduced;
            output.frontier.failed = output.frontier.failed.saturating_sub(reduced as u32);
            output.frontier.trusted += reduced as u32;
            let stats = CegarStats {
                refinement_iterations: 1,
                spurious_eliminated: reduced,
                real_counterexamples: output.vcs_failed,
                predicates_added: reduced,
                hit_limit: false,
            };
            (output, stats)
        }
    }

    /// A certification stage that counts proved VCs.
    struct MockCertificationStage;

    impl CertificationStage for MockCertificationStage {
        fn certify(&self, _: &Path, output: &VerifyOutput) -> CertificationSummary {
            CertificationSummary {
                certificates_generated: output.frontier.trusted as usize,
                certificates_skipped: output.vcs_failed,
                lean5_certified: 0,
                lean5_rejected: 0,
                time_ms: 1,
            }
        }
    }

    // -- Helpers ------------------------------------------------------------

    fn frontier(trusted: u32, failed: u32) -> ProofFrontier {
        ProofFrontier {
            trusted,
            certified: 0,
            runtime_checked: 0,
            failed,
            unknown: 0,
        }
    }

    fn verify_output(trusted: u32, failed: u32) -> VerifyOutput {
        VerifyOutput {
            frontier: frontier(trusted, failed),
            fingerprint: None,
            vcs_dispatched: (trusted + failed) as usize,
            vcs_failed: failed as usize,
            detailed_results: None,
        }
    }

    fn test_path() -> PathBuf {
        PathBuf::from("/tmp/pipeline_test.rs")
    }

    fn default_config() -> PipelineConfig {
        PipelineConfig {
            enable_cegar: false,
            enable_certification: false,
            ..Default::default()
        }
    }

    // -- Test cases ---------------------------------------------------------

    #[test]
    fn test_pipeline_all_proved_first_pass() {
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut pipeline = Pipeline::new(
            default_config(),
            &verify,
            &strengthen,
            &backprop,
        );
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::AllProved {
                iterations: 1,
                certificates: 0,
            }
        );
        assert_eq!(result.final_frontier.trusted, 5);
        assert_eq!(result.final_frontier.failed, 0);
        assert_eq!(result.history.len(), 1);
    }

    #[test]
    fn test_pipeline_with_cegar_improves_result() {
        // Initial verify: 2 trusted, 3 failed.
        // CEGAR reduces by 2: 4 trusted, 1 failed.
        // Strengthen proposes, backprop applies, next iteration proves all.
        let verify = MockVerify::new(vec![
            verify_output(2, 3),
            verify_output(5, 0),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            enable_cegar: true,
            enable_certification: false,
            ..Default::default()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop)
            .with_cegar(Box::new(MockCegarStage { reduction: 2 }));

        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::AllProved {
                iterations: 2,
                certificates: 0,
            }
        );
        // First iteration should have CEGAR stats.
        assert!(result.history[0].cegar_stats.is_some());
        let stats = result.history[0].cegar_stats.as_ref().unwrap();
        assert_eq!(stats.spurious_eliminated, 2);
        assert_eq!(stats.refinement_iterations, 1);
        assert_eq!(result.total_cegar_refinements, 1);
    }

    #[test]
    fn test_pipeline_with_certification() {
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let config = PipelineConfig {
            enable_cegar: false,
            enable_certification: true,
            ..Default::default()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop)
            .with_certification(Box::new(MockCertificationStage));

        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::AllProved {
                iterations: 1,
                certificates: 5,
            }
        );
        assert_eq!(result.total_certificates, 5);
        // Certification summary in history.
        let cert = result.history[0].certification.as_ref().unwrap();
        assert_eq!(cert.certificates_generated, 5);
        assert_eq!(cert.certificates_skipped, 0);
    }

    #[test]
    fn test_pipeline_convergence_stops_loop() {
        // Same frontier (with failures) for 2 rounds -> converged.
        let verify = MockVerify::new(vec![
            verify_output(3, 2),
            verify_output(3, 2),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            max_iterations: 10,
            stable_round_limit: 2,
            stall_threshold: 5, // high, so we converge before stall
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::Converged {
                iterations: 2,
                stable_rounds: 2,
                vcs_failed: 2,
            }
        );
    }

    #[test]
    fn test_pipeline_regression_stops_loop() {
        let verify = MockVerify::new(vec![
            verify_output(4, 1),
            verify_output(3, 2),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let mut pipeline = Pipeline::new(default_config(), &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::Regressed { iterations: 2 }
        );
    }

    #[test]
    fn test_pipeline_no_proposals_stops_loop() {
        let verify = MockVerify::new(vec![verify_output(2, 3)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut pipeline = Pipeline::new(default_config(), &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::NoProposals {
                iterations: 1,
                vcs_failed: 3,
            }
        );
    }

    #[test]
    fn test_pipeline_backprop_applies_nothing_stops() {
        let verify = MockVerify::new(vec![verify_output(2, 3)]);
        let strengthen = MockStrengthen { proposal_count: 2 };
        let backprop = NoOpBackprop;

        let config = PipelineConfig {
            allow_rewrite: true,
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::NoProposals {
                iterations: 1,
                vcs_failed: 3,
            }
        );
        assert_eq!(result.history[0].proposals, 2);
        assert_eq!(result.history[0].applied, 0);
    }

    #[test]
    fn test_pipeline_iteration_limit() {
        let verify = MockVerify::new(vec![
            verify_output(1, 4),
            verify_output(2, 3),
            verify_output(3, 2),
            verify_output(4, 1),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            max_iterations: 3,
            stall_threshold: 10, // high so stall doesn't trigger
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::IterationLimit { iterations: 4 }
        );
    }

    #[test]
    fn test_pipeline_stall_detection() {
        // Same frontier for 3 rounds with stall_threshold=3 -> Stalled.
        // Need stable_round_limit high enough that Converged doesn't fire first.
        let verify = MockVerify::new(vec![
            verify_output(3, 2),
            verify_output(3, 2),
            verify_output(3, 2),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            max_iterations: 10,
            stable_round_limit: 5, // high so Converged doesn't trigger
            stall_threshold: 3,
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::Stalled {
                iterations: 3,
                stale_iterations: 3,
                vcs_failed: 2,
            }
        );
    }

    #[test]
    fn test_pipeline_cegar_plus_certification_end_to_end() {
        // Full pipeline: CEGAR eliminates 1 spurious, certification counts proved.
        let verify = MockVerify::new(vec![
            verify_output(3, 2), // initial: 3 proved, 2 failed
            verify_output(5, 0), // second pass: all proved
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            enable_cegar: true,
            enable_certification: true,
            ..Default::default()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop)
            .with_cegar(Box::new(MockCegarStage { reduction: 1 }))
            .with_certification(Box::new(MockCertificationStage));

        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::AllProved {
                iterations: 2,
                certificates: 9, // 4 from iter0 (after CEGAR) + 5 from iter1
            }
        );
        assert_eq!(result.total_certificates, 9);
        assert_eq!(result.total_cegar_refinements, 1);
    }

    #[test]
    fn test_pipeline_without_cegar_builder() {
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let config = PipelineConfig {
            enable_cegar: true, // enabled in config...
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop)
            .without_cegar(); // ...but disabled via builder

        let result = pipeline.run(&test_path());

        // Should still work, just without CEGAR.
        assert_eq!(
            result.outcome,
            PipelineOutcome::AllProved {
                iterations: 1,
                certificates: 0,
            }
        );
        assert!(result.history[0].cegar_stats.is_none());
    }

    #[test]
    fn test_pipeline_custom_convergence_stage() {
        /// A convergence stage that always says Continue.
        struct AlwaysContinue;

        impl ConvergenceStage for AlwaysContinue {
            fn observe(&mut self, _: u32, _: &VerifyOutput) -> ConvergenceDecision {
                ConvergenceDecision::Continue {
                    verdict: trust_convergence::StepVerdict::Improved,
                }
            }
            fn verdict(&self) -> ConvergenceVerdict {
                ConvergenceVerdict::InProgress
            }
            fn consecutive_stable_count(&self) -> usize {
                0
            }
        }

        let verify = MockVerify::new(vec![verify_output(2, 3)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut pipeline = Pipeline::new(default_config(), &verify, &strengthen, &backprop)
            .with_convergence(Box::new(AlwaysContinue));

        let result = pipeline.run(&test_path());

        // Custom convergence says Continue, but strengthen has no proposals -> NoProposals.
        assert_eq!(
            result.outcome,
            PipelineOutcome::NoProposals {
                iterations: 1,
                vcs_failed: 3,
            }
        );
    }

    #[test]
    fn test_pipeline_history_tracks_all_iterations() {
        let verify = MockVerify::new(vec![
            verify_output(1, 4),
            verify_output(3, 2),
            verify_output(5, 0),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let mut pipeline = Pipeline::new(default_config(), &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(result.history.len(), 3);
        assert_eq!(result.history[0].frontier.trusted, 1);
        assert_eq!(result.history[1].frontier.trusted, 3);
        assert_eq!(result.history[2].frontier.trusted, 5);
        assert_eq!(result.history[2].vcs_failed, 0);
    }

    #[test]
    fn test_pipeline_default_config() {
        let config = PipelineConfig::default();
        assert_eq!(config.max_iterations, 8);
        assert_eq!(config.stable_round_limit, 2);
        assert!(config.allow_rewrite);
        assert!(config.enable_cegar);
        assert!(config.enable_certification);
        assert_eq!(config.stall_threshold, 3);
    }

    #[test]
    fn test_pipeline_cegar_skips_when_no_failures() {
        // If verify returns 0 failures, CEGAR should not be invoked.
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let config = PipelineConfig {
            enable_cegar: true,
            enable_certification: false,
            ..Default::default()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop)
            .with_cegar(Box::new(MockCegarStage { reduction: 10 }));

        let result = pipeline.run(&test_path());

        // CEGAR should not have been invoked (no failures to refine).
        assert!(result.history[0].cegar_stats.is_none());
        assert_eq!(result.total_cegar_refinements, 0);
    }

    #[test]
    fn test_pipeline_fingerprint_convergence() {
        let mut out1 = verify_output(3, 1);
        out1.fingerprint = Some("abc123".into());
        let mut out2 = verify_output(3, 1);
        out2.fingerprint = Some("abc123".into());

        let verify = MockVerify::new(vec![out1, out2]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let config = PipelineConfig {
            max_iterations: 10,
            stable_round_limit: 2,
            stall_threshold: 5,
            ..default_config()
        };

        let mut pipeline = Pipeline::new(config, &verify, &strengthen, &backprop);
        let result = pipeline.run(&test_path());

        assert_eq!(
            result.outcome,
            PipelineOutcome::Converged {
                iterations: 2,
                stable_rounds: 2,
                vcs_failed: 1,
            }
        );
    }
}
