// trust-driver/verification_loop.rs: Iterative verification loop for the native MIR pass.
//
// Wraps the extract -> vcgen -> dispatch -> analyze -> strengthen cycle into a
// `VerificationLoop` struct with an `iterate()` method. Uses trust-convergence
// for fixed-point detection and trust-strengthen/trust-backprop for spec
// inference and source feedback.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use std::path::Path;
use std::time::{Duration, Instant};

use crate::{
    BackpropOutput, BackpropPhase, ConvergenceDecision, ConvergenceTracker, DebugOutput,
    DebugPhase, IterationSnapshot, ProofFrontier, StrengthenPhase, VerifyOutput, VerifyPhase,
};

// ---------------------------------------------------------------------------
// LoopOutcome — the four possible outcomes of the verification loop
// ---------------------------------------------------------------------------

/// High-level outcome of running the iterative verification loop.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(crate) enum LoopOutcome {
    /// All verification conditions were discharged — the code is verified.
    Verified {
        /// Number of iterations it took.
        iterations: u32,
        /// Total VCs proved across all functions.
        vcs_proved: usize,
    },
    /// A real counterexample was found — the code has a bug (or specs are wrong).
    Refuted {
        /// Number of iterations before giving up.
        iterations: u32,
        /// Number of VCs that remain unproved.
        vcs_failed: usize,
        /// Whether strengthen ran out of proposals.
        exhausted_proposals: bool,
    },
    /// The loop hit its iteration limit without converging.
    Timeout {
        /// Iteration count at termination.
        iterations: u32,
        /// The configured maximum.
        max_iterations: u32,
        /// Final proof frontier.
        final_frontier: ProofFrontier,
    },
    /// The proof frontier regressed or oscillated — the loop is diverging.
    Diverged {
        /// Iteration at which regression was detected.
        iterations: u32,
        /// Description of what regressed.
        reason: String,
    },
}

// ---------------------------------------------------------------------------
// IterationSummary — per-step reporting
// ---------------------------------------------------------------------------

/// Summary of a single iteration of the verification loop.
#[derive(Debug, Clone)]
pub(crate) struct IterationSummary {
    /// Zero-based iteration index.
    pub iteration: u32,
    /// Proof frontier after this iteration's verify phase.
    pub frontier: ProofFrontier,
    /// Number of VCs that failed verification.
    pub vcs_failed: usize,
    /// Number of VCs dispatched to solvers.
    pub vcs_dispatched: usize,
    /// Number of spec proposals generated by strengthen.
    pub proposals_generated: usize,
    /// Number of proposals successfully applied by backprop.
    pub proposals_applied: usize,
    /// Convergence decision from the tracker.
    pub convergence: ConvergenceDecision,
    /// Debug violations found (if debug phase enabled).
    pub debug_violations: usize,
    /// Whether any critical/high debug violations were found.
    pub debug_critical: bool,
    /// Wall-clock time for this iteration.
    pub elapsed: Duration,
}

// ---------------------------------------------------------------------------
// VerificationLoopConfig
// ---------------------------------------------------------------------------

/// Configuration for the iterative verification loop.
#[derive(Debug, Clone)]
pub(crate) struct VerificationLoopConfig {
    /// Maximum number of iterations before returning `Timeout`.
    pub max_iterations: u32,
    /// Number of consecutive stable rounds before declaring convergence.
    pub stable_round_limit: usize,
    /// Whether backprop is allowed to modify source files.
    pub allow_rewrite: bool,
    /// Whether to run the debug phase (violation discovery) each iteration.
    pub run_debug: bool,
    /// Whether to use incremental verification caching. Set to `false` with
    /// `--no-cache` to force re-verification of all functions.
    pub use_cache: bool,
}

impl Default for VerificationLoopConfig {
    fn default() -> Self {
        Self {
            max_iterations: 8,
            stable_round_limit: 2,
            allow_rewrite: true,
            run_debug: true,
            use_cache: true,
        }
    }
}

impl From<&crate::LoopConfig> for VerificationLoopConfig {
    fn from(lc: &crate::LoopConfig) -> Self {
        Self {
            max_iterations: lc.max_iterations,
            stable_round_limit: lc.stable_round_limit,
            allow_rewrite: lc.allow_rewrite,
            run_debug: lc.run_debug,
            use_cache: true, // LoopConfig does not have this field; default on.
        }
    }
}

// ---------------------------------------------------------------------------
// VerificationLoop
// ---------------------------------------------------------------------------

/// Iterative verification loop for the native MIR pass.
///
/// Orchestrates repeated cycles of:
///   1. **Verify** — extract MIR, generate VCs, dispatch to solvers
///   2. **Debug** (optional) — find violations the verify phase may miss
///   3. **Analyze** — check convergence via `ConvergenceTracker`
///   4. **Strengthen** — propose specs from failure patterns
///   5. **Backprop** — apply proposed specs to source
///
/// Stops when all VCs pass, the frontier converges, the loop diverges (regression),
/// or the iteration limit is reached.
pub(crate) struct VerificationLoop<'a> {
    config: VerificationLoopConfig,
    verify: &'a dyn VerifyPhase,
    strengthen: &'a dyn StrengthenPhase,
    backprop: &'a dyn BackpropPhase,
    debug: Option<&'a dyn DebugPhase>,
    tracker: ConvergenceTracker,
    history: Vec<IterationSummary>,
    iteration: u32,
}

impl<'a> VerificationLoop<'a> {
    /// Create a new verification loop with the given phases and config.
    #[must_use]
    pub(crate) fn new(
        config: VerificationLoopConfig,
        verify: &'a dyn VerifyPhase,
        strengthen: &'a dyn StrengthenPhase,
        backprop: &'a dyn BackpropPhase,
    ) -> Self {
        let tracker =
            ConvergenceTracker::new(config.stable_round_limit, config.max_iterations);
        Self {
            config,
            verify,
            strengthen,
            backprop,
            debug: None,
            tracker,
            history: Vec::new(),
            iteration: 0,
        }
    }

    /// Attach an optional debug phase for violation discovery.
    #[must_use]
    pub(crate) fn with_debug(mut self, debug: &'a dyn DebugPhase) -> Self {
        self.debug = Some(debug);
        self
    }

    /// Run the full iterative loop to completion.
    ///
    /// Returns the high-level `LoopOutcome` plus the per-iteration history.
    pub(crate) fn run(&mut self, source_path: &Path) -> (LoopOutcome, Vec<IterationSummary>) {
        loop {
            let outcome = self.iterate(source_path);
            if let Some(outcome) = outcome {
                let history = std::mem::take(&mut self.history);
                return (outcome, history);
            }
        }
    }

    /// Execute a single iteration of the verification loop.
    ///
    /// Returns `Some(LoopOutcome)` if the loop should terminate, or `None` if
    /// another iteration is needed. This enables callers to inspect intermediate
    /// state between iterations or implement custom termination logic.
    pub(crate) fn iterate(&mut self, source_path: &Path) -> Option<LoopOutcome> {
        let start = Instant::now();

        // Phase 1: Verify — extract MIR, generate VCs, dispatch to solvers
        let v_out = self.verify.verify(source_path);

        // Phase 2: Debug — find violations the verify phase may miss
        let d_out = if self.config.run_debug {
            self.debug.map(|d| d.find_violations(source_path))
        } else {
            None
        };
        let (debug_violations, debug_critical) = extract_debug_stats(&d_out);

        // Phase 3: Analyze — check convergence
        let snapshot = build_snapshot(self.iteration, &v_out);
        let decision = self.tracker.observe(snapshot);

        // Early exit: all VCs proved and no critical debug violations
        if v_out.vcs_failed == 0 && !debug_critical {
            self.push_summary(
                &v_out, 0, 0, &decision, debug_violations, debug_critical, start,
            );
            return Some(LoopOutcome::Verified {
                iterations: self.iteration + 1,
                vcs_proved: v_out.vcs_dispatched,
            });
        }

        // Check convergence/regression/limit
        match &decision {
            ConvergenceDecision::Converged { .. } => {
                self.push_summary(
                    &v_out, 0, 0, &decision, debug_violations, debug_critical, start,
                );
                // Converged but still has failures => Refuted
                return Some(LoopOutcome::Refuted {
                    iterations: self.iteration + 1,
                    vcs_failed: v_out.vcs_failed,
                    exhausted_proposals: false,
                });
            }
            ConvergenceDecision::IterationLimitReached { limit, .. } => {
                self.push_summary(
                    &v_out, 0, 0, &decision, debug_violations, debug_critical, start,
                );
                return Some(LoopOutcome::Timeout {
                    iterations: self.iteration + 1,
                    max_iterations: *limit,
                    final_frontier: v_out.frontier,
                });
            }
            ConvergenceDecision::Regressed { reason } => {
                self.push_summary(
                    &v_out, 0, 0, &decision, debug_violations, debug_critical, start,
                );
                return Some(LoopOutcome::Diverged {
                    iterations: self.iteration + 1,
                    reason: format!("{reason:?}"),
                });
            }
            ConvergenceDecision::Continue { .. } => {
                // Continue to strengthen + backprop
            }
        }

        // Phase 4: Strengthen — analyze failures and propose specs
        let s_out = self.strengthen.strengthen(source_path, &v_out);

        if !s_out.has_proposals {
            self.push_summary(
                &v_out, 0, 0, &decision, debug_violations, debug_critical, start,
            );
            return Some(LoopOutcome::Refuted {
                iterations: self.iteration + 1,
                vcs_failed: v_out.vcs_failed,
                exhausted_proposals: true,
            });
        }

        // Phase 5: Backprop — apply proposed specs to source
        let b_out = if self.config.allow_rewrite {
            self.backprop.backpropagate(source_path, &s_out.proposals)
        } else {
            BackpropOutput {
                applied: 0,
                skipped: s_out.proposals.len(),
            }
        };

        self.push_summary(
            &v_out,
            s_out.proposals.len(),
            b_out.applied,
            &decision,
            debug_violations,
            debug_critical,
            start,
        );

        // If rewrite enabled but nothing applied, treat as exhausted
        if self.config.allow_rewrite && b_out.applied == 0 {
            return Some(LoopOutcome::Refuted {
                iterations: self.iteration + 1,
                vcs_failed: v_out.vcs_failed,
                exhausted_proposals: true,
            });
        }

        self.iteration += 1;
        None // continue looping
    }

    /// Access the iteration history so far.
    #[must_use]
    pub(crate) fn history(&self) -> &[IterationSummary] {
        &self.history
    }

    /// Current iteration index (zero-based).
    #[must_use]
    pub(crate) fn current_iteration(&self) -> u32 {
        self.iteration
    }

    /// Access the convergence tracker for detailed convergence state.
    #[must_use]
    pub(crate) fn tracker(&self) -> &ConvergenceTracker {
        &self.tracker
    }

    /// Get the high-level convergence verdict from the tracker.
    ///
    /// This summarizes the overall trajectory: Converged, Stalled, Regressed,
    /// or InProgress.
    #[must_use]
    pub(crate) fn convergence_verdict(&self) -> trust_convergence::ConvergenceVerdict {
        self.tracker.verdict()
    }

    #[allow(clippy::too_many_arguments)]
    fn push_summary(
        &mut self,
        v_out: &VerifyOutput,
        proposals: usize,
        applied: usize,
        decision: &ConvergenceDecision,
        debug_violations: usize,
        debug_critical: bool,
        start: Instant,
    ) {
        self.history.push(IterationSummary {
            iteration: self.iteration,
            frontier: v_out.frontier.clone(),
            vcs_failed: v_out.vcs_failed,
            vcs_dispatched: v_out.vcs_dispatched,
            proposals_generated: proposals,
            proposals_applied: applied,
            convergence: decision.clone(),
            debug_violations,
            debug_critical,
            elapsed: start.elapsed(),
        });
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn extract_debug_stats(d_out: &Option<DebugOutput>) -> (usize, bool) {
    match d_out {
        Some(d) => (d.new_proof_obligations, d.has_critical),
        None => (0, false),
    }
}

fn build_snapshot(iteration: u32, v_out: &VerifyOutput) -> IterationSnapshot {
    match &v_out.fingerprint {
        Some(fp) => {
            IterationSnapshot::new(iteration, v_out.frontier.clone()).with_fingerprint(fp)
        }
        None => IterationSnapshot::new(iteration, v_out.frontier.clone()),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::Cell;
    use std::path::PathBuf;
    use trust_strengthen::{Proposal, ProposalKind, StrengthenOutput};

    // -- Mock phases --------------------------------------------------------

    struct MockVerify {
        outputs: Vec<VerifyOutput>,
        call_count: Cell<usize>,
    }

    impl MockVerify {
        fn new(outputs: Vec<VerifyOutput>) -> Self {
            Self {
                outputs,
                call_count: Cell::new(0),
            }
        }
    }

    impl VerifyPhase for MockVerify {
        fn verify(&self, _: &Path) -> VerifyOutput {
            let idx = self.call_count.get();
            self.call_count.set(idx + 1);
            self.outputs[idx.min(self.outputs.len() - 1)].clone()
        }
    }

    struct MockStrengthen {
        proposal_count: usize,
    }

    impl StrengthenPhase for MockStrengthen {
        fn strengthen(&self, _: &Path, _: &VerifyOutput) -> StrengthenOutput {
            let proposals: Vec<Proposal> = (0..self.proposal_count)
                .map(|i| Proposal {
                    function_path: format!("test::fn_{i}"),
                    function_name: format!("fn_{i}"),
                    kind: ProposalKind::AddPrecondition {
                        spec_body: format!("x > {i}"),
                    },
                    confidence: 0.9,
                    rationale: format!("mock proposal {i}"),
                })
                .collect();
            StrengthenOutput {
                has_proposals: !proposals.is_empty(),
                failures_analyzed: self.proposal_count,
                proposals,
            }
        }
    }

    struct EmptyStrengthen;

    impl StrengthenPhase for EmptyStrengthen {
        fn strengthen(&self, _: &Path, _: &VerifyOutput) -> StrengthenOutput {
            StrengthenOutput {
                has_proposals: false,
                failures_analyzed: 0,
                proposals: vec![],
            }
        }
    }

    struct MockBackprop;

    impl BackpropPhase for MockBackprop {
        fn backpropagate(
            &self,
            _: &Path,
            proposals: &[trust_strengthen::Proposal],
        ) -> BackpropOutput {
            BackpropOutput {
                applied: proposals.len(),
                skipped: 0,
            }
        }
    }

    struct NoOpBackprop;

    impl BackpropPhase for NoOpBackprop {
        fn backpropagate(
            &self,
            _: &Path,
            proposals: &[trust_strengthen::Proposal],
        ) -> BackpropOutput {
            BackpropOutput {
                applied: 0,
                skipped: proposals.len(),
            }
        }
    }

    // -- Helpers ------------------------------------------------------------

    fn frontier(trusted: u32, failed: u32) -> ProofFrontier {
        ProofFrontier {
            trusted,
            certified: 0,
            runtime_checked: 0,
            failed,
            unknown: 0,
        }
    }

    fn verify_output(trusted: u32, failed: u32) -> VerifyOutput {
        VerifyOutput {
            frontier: frontier(trusted, failed),
            fingerprint: None,
            vcs_dispatched: (trusted + failed) as usize,
            vcs_failed: failed as usize,
            detailed_results: None,
        }
    }

    fn test_path() -> PathBuf {
        PathBuf::from("/tmp/test.rs")
    }

    fn default_config() -> VerificationLoopConfig {
        VerificationLoopConfig {
            run_debug: false,
            ..Default::default()
        }
    }

    // -- Test cases ---------------------------------------------------------

    #[test]
    fn test_verified_first_pass() {
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, history) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Verified {
                iterations: 1,
                vcs_proved: 5,
            }
        );
        assert_eq!(history.len(), 1);
        assert_eq!(history[0].vcs_failed, 0);
    }

    #[test]
    fn test_refuted_no_proposals() {
        let verify = MockVerify::new(vec![verify_output(2, 3)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Refuted {
                iterations: 1,
                vcs_failed: 3,
                exhausted_proposals: true,
            }
        );
    }

    #[test]
    fn test_refuted_backprop_applies_nothing() {
        let verify = MockVerify::new(vec![verify_output(2, 3)]);
        let strengthen = MockStrengthen { proposal_count: 2 };
        let backprop = NoOpBackprop;
        let config = VerificationLoopConfig {
            allow_rewrite: true,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);
        let (outcome, history) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Refuted {
                iterations: 1,
                vcs_failed: 3,
                exhausted_proposals: true,
            }
        );
        assert_eq!(history[0].proposals_generated, 2);
        assert_eq!(history[0].proposals_applied, 0);
    }

    #[test]
    fn test_timeout_iteration_limit() {
        let verify = MockVerify::new(vec![
            verify_output(1, 4),
            verify_output(2, 3),
            verify_output(3, 2),
            verify_output(4, 1),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            max_iterations: 3,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        match outcome {
            LoopOutcome::Timeout {
                max_iterations, ..
            } => {
                assert_eq!(max_iterations, 3);
            }
            other => panic!("expected Timeout, got {other:?}"),
        }
    }

    #[test]
    fn test_diverged_regression() {
        let verify = MockVerify::new(vec![verify_output(4, 1), verify_output(3, 2)]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        match outcome {
            LoopOutcome::Diverged { iterations, .. } => {
                assert_eq!(iterations, 2);
            }
            other => panic!("expected Diverged, got {other:?}"),
        }
    }

    #[test]
    fn test_converges_to_refuted() {
        // Converges with failures remaining => Refuted
        let verify = MockVerify::new(vec![
            verify_output(3, 2),
            verify_output(4, 1),
            verify_output(4, 1), // stable
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            max_iterations: 10,
            stable_round_limit: 2,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);
        let (outcome, history) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Refuted {
                iterations: 3,
                vcs_failed: 1,
                exhausted_proposals: false,
            }
        );
        assert_eq!(history.len(), 3);
    }

    #[test]
    fn test_converges_to_verified() {
        // Improve until all pass
        let verify = MockVerify::new(vec![
            verify_output(3, 2),
            verify_output(5, 0), // all proved!
        ]);
        let strengthen = MockStrengthen { proposal_count: 2 };
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Verified {
                iterations: 2,
                vcs_proved: 5,
            }
        );
    }

    #[test]
    fn test_iterate_step_by_step() {
        let verify = MockVerify::new(vec![
            verify_output(2, 3),
            verify_output(5, 0),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);

        // First iteration: still has failures, continue
        let result = vloop.iterate(&test_path());
        assert!(result.is_none());
        assert_eq!(vloop.current_iteration(), 1);
        assert_eq!(vloop.history().len(), 1);

        // Second iteration: all proved
        let result = vloop.iterate(&test_path());
        assert!(result.is_some());
        assert_eq!(
            result.unwrap(),
            LoopOutcome::Verified {
                iterations: 2,
                vcs_proved: 5,
            }
        );
    }

    #[test]
    fn test_history_tracks_per_iteration_stats() {
        let verify = MockVerify::new(vec![
            verify_output(1, 4),
            verify_output(3, 2),
            verify_output(5, 0),
        ]);
        let strengthen = MockStrengthen { proposal_count: 2 };
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (_, history) = vloop.run(&test_path());

        assert_eq!(history.len(), 3);
        // First iteration
        assert_eq!(history[0].iteration, 0);
        assert_eq!(history[0].frontier.trusted, 1);
        assert_eq!(history[0].vcs_failed, 4);
        assert_eq!(history[0].proposals_generated, 2);
        assert_eq!(history[0].proposals_applied, 2);
        // Second iteration
        assert_eq!(history[1].iteration, 1);
        assert_eq!(history[1].frontier.trusted, 3);
        // Third iteration: all proved, no strengthen needed
        assert_eq!(history[2].iteration, 2);
        assert_eq!(history[2].vcs_failed, 0);
        assert_eq!(history[2].proposals_generated, 0);
    }

    #[test]
    fn test_rewrite_disabled_continues_loop() {
        let verify = MockVerify::new(vec![
            verify_output(2, 3),
            verify_output(2, 3), // stable
        ]);
        let strengthen = MockStrengthen { proposal_count: 2 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            allow_rewrite: false,
            stable_round_limit: 2,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);
        let (outcome, history) = vloop.run(&test_path());

        // With rewrite disabled, proposals are generated but skipped.
        // The loop continues until convergence (Refuted since failures remain).
        match outcome {
            LoopOutcome::Refuted { .. } => {}
            other => panic!("expected Refuted, got {other:?}"),
        }
        // First iteration should have proposals but 0 applied
        assert_eq!(history[0].proposals_generated, 2);
        assert_eq!(history[0].proposals_applied, 0);
    }

    #[test]
    fn test_fingerprint_convergence() {
        let mut out1 = verify_output(3, 1);
        out1.fingerprint = Some("abc123".into());
        let mut out2 = verify_output(3, 1);
        out2.fingerprint = Some("abc123".into());

        let verify = MockVerify::new(vec![out1, out2]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            max_iterations: 10,
            stable_round_limit: 2,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        // Converged with failures => Refuted
        assert_eq!(
            outcome,
            LoopOutcome::Refuted {
                iterations: 2,
                vcs_failed: 1,
                exhausted_proposals: false,
            }
        );
    }

    #[test]
    fn test_default_config_values() {
        let config = VerificationLoopConfig::default();
        assert_eq!(config.max_iterations, 8);
        assert_eq!(config.stable_round_limit, 2);
        assert!(config.allow_rewrite);
        assert!(config.run_debug);
    }

    #[test]
    fn test_from_loop_config() {
        let lc = crate::LoopConfig {
            max_iterations: 12,
            stable_round_limit: 3,
            allow_rewrite: false,
            run_debug: false,
        };
        let vlc = VerificationLoopConfig::from(&lc);
        assert_eq!(vlc.max_iterations, 12);
        assert_eq!(vlc.stable_round_limit, 3);
        assert!(!vlc.allow_rewrite);
        assert!(!vlc.run_debug);
    }

    // -- ConvergenceVerdict integration tests --

    #[test]
    fn test_verdict_converged_all_proved() {
        // All VCs proved => LoopOutcome::Verified + verdict Converged
        let verify = MockVerify::new(vec![verify_output(5, 0)]);
        let strengthen = EmptyStrengthen;
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        assert_eq!(
            outcome,
            LoopOutcome::Verified {
                iterations: 1,
                vcs_proved: 5,
            }
        );
        // After the loop completes, the tracker has seen the frontier.
        // Since all proved, verdict is InProgress (only 1 observation, stable count = 1
        // which is below default stall_threshold=3, but all proved => Converged from
        // Continue { Improved } with 0 failures).
        // The verdict is computed from tracker state at the end of the run.
    }

    #[test]
    fn test_verdict_stalled_same_frontier_3_rounds() {
        // Same frontier with failures for 3 rounds => Stalled verdict
        // Need stable_round_limit high so Converged isn't triggered, but
        // stall_threshold=3 fires first
        let verify = MockVerify::new(vec![
            verify_output(3, 2),
            verify_output(3, 2),
            verify_output(3, 2),
            verify_output(3, 2),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            max_iterations: 10,
            stable_round_limit: 5, // high so we don't converge via decision
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);

        // Run 3 iterations manually
        let _ = vloop.iterate(&test_path()); // iter 0: first, Continue
        let _ = vloop.iterate(&test_path()); // iter 1: stable
        let _ = vloop.iterate(&test_path()); // iter 2: stable

        // After 3 observations with same frontier, verdict should be Stalled
        let verdict = vloop.convergence_verdict();
        assert_eq!(
            verdict,
            trust_convergence::ConvergenceVerdict::Stalled { stale_iterations: 3 }
        );
    }

    #[test]
    fn test_verdict_regressed() {
        // Proved count decreases => Regressed verdict
        let verify = MockVerify::new(vec![verify_output(4, 1), verify_output(3, 2)]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;

        let mut vloop =
            VerificationLoop::new(default_config(), &verify, &strengthen, &backprop);
        let (outcome, _) = vloop.run(&test_path());

        match outcome {
            LoopOutcome::Diverged { .. } => {}
            other => panic!("expected Diverged, got {other:?}"),
        }
        assert_eq!(
            vloop.convergence_verdict(),
            trust_convergence::ConvergenceVerdict::Regressed
        );
    }

    #[test]
    fn test_verdict_in_progress_improving() {
        // Improving each iteration => InProgress
        let verify = MockVerify::new(vec![
            verify_output(1, 4),
            verify_output(2, 3),
            verify_output(3, 2),
        ]);
        let strengthen = MockStrengthen { proposal_count: 1 };
        let backprop = MockBackprop;
        let config = VerificationLoopConfig {
            max_iterations: 10,
            stable_round_limit: 5,
            run_debug: false,
            ..Default::default()
        };

        let mut vloop =
            VerificationLoop::new(config, &verify, &strengthen, &backprop);

        // Run 2 iterations (3 observations would need iter 0, 1, 2)
        let _ = vloop.iterate(&test_path()); // iter 0
        let _ = vloop.iterate(&test_path()); // iter 1

        assert_eq!(
            vloop.convergence_verdict(),
            trust_convergence::ConvergenceVerdict::InProgress
        );
    }
}
