// trust-strengthen/confidence.rs: Confidence scoring and ranking for spec proposals
//
// Provides multi-factor confidence estimation for spec proposals, ranking
// strategies, and calibration tracking to improve scoring over time.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use trust_types::fx::FxHashMap;

use crate::proposer::{Proposal, ProposalKind};

/// A confidence score with a breakdown of contributing factors.
#[derive(Debug, Clone, PartialEq)]
pub struct ConfidenceScore {
    /// Overall confidence in [0.0, 1.0].
    pub value: f64,
    /// Breakdown of individual factors that contributed to the score.
    pub breakdown: ConfidenceBreakdown,
}

impl ConfidenceScore {
    /// Create a new confidence score, clamping value to [0.0, 1.0].
    #[must_use]
    pub fn new(value: f64, breakdown: ConfidenceBreakdown) -> Self {
        Self { value: value.clamp(0.0, 1.0), breakdown }
    }
}

/// Breakdown of factors contributing to a confidence score.
#[derive(Debug, Clone, PartialEq)]
pub struct ConfidenceBreakdown {
    /// Reliability of the proposal source (heuristic, WP, LLM, etc.).
    pub source_reliability: f64,
    /// Score based on formula complexity (simpler = higher).
    pub formula_complexity: f64,
    /// How many counterexamples this spec addresses.
    pub counterexample_coverage: f64,
    /// Historical success rate of similar specs.
    pub historical_success: f64,
}

impl Default for ConfidenceBreakdown {
    fn default() -> Self {
        Self {
            source_reliability: 0.5,
            formula_complexity: 0.5,
            counterexample_coverage: 0.0,
            historical_success: 0.5,
        }
    }
}

/// The source that generated a proposal, used for source reliability scoring.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ProposalSource {
    /// Generated by heuristic pattern matching.
    Heuristic,
    /// Generated by weakest precondition calculus.
    WeakestPrecondition,
    /// Generated by LLM inference.
    Llm,
    /// Generated by counterexample analysis.
    CounterexampleGuided,
    /// Generated by signature-based inference.
    SignatureBased,
}

impl ProposalSource {
    /// Default reliability score for this source.
    #[must_use]
    pub fn default_reliability(self) -> f64 {
        match self {
            Self::Heuristic => 0.6,
            Self::WeakestPrecondition => 0.8,
            Self::Llm => 0.5,
            Self::CounterexampleGuided => 0.75,
            Self::SignatureBased => 0.4,
        }
    }
}

/// Configurable weights for combining confidence factors.
#[derive(Debug, Clone, PartialEq)]
pub struct ConfidenceWeights {
    /// Weight for source reliability factor.
    pub source_reliability: f64,
    /// Weight for formula complexity factor.
    pub formula_complexity: f64,
    /// Weight for counterexample coverage factor.
    pub counterexample_coverage: f64,
    /// Weight for historical success factor.
    pub historical_success: f64,
}

impl Default for ConfidenceWeights {
    fn default() -> Self {
        Self {
            source_reliability: 0.35,
            formula_complexity: 0.20,
            counterexample_coverage: 0.25,
            historical_success: 0.20,
        }
    }
}

impl ConfidenceWeights {
    /// Normalize weights so they sum to 1.0.
    #[must_use]
    pub fn normalized(&self) -> Self {
        let total = self.source_reliability
            + self.formula_complexity
            + self.counterexample_coverage
            + self.historical_success;
        if total <= f64::EPSILON {
            return Self::default();
        }
        Self {
            source_reliability: self.source_reliability / total,
            formula_complexity: self.formula_complexity / total,
            counterexample_coverage: self.counterexample_coverage / total,
            historical_success: self.historical_success / total,
        }
    }
}

/// Combines multiple factors into a single confidence score.
pub struct ConfidenceEstimator {
    /// Weights for combining factors.
    weights: ConfidenceWeights,
    /// Override reliability scores per source.
    source_overrides: FxHashMap<ProposalSource, f64>,
    /// Historical success tracker for calibration.
    calibration: CalibrationTracker,
}

impl ConfidenceEstimator {
    /// Create a new estimator with default weights.
    #[must_use]
    pub fn new() -> Self {
        Self {
            weights: ConfidenceWeights::default(),
            source_overrides: FxHashMap::default(),
            calibration: CalibrationTracker::new(),
        }
    }

    /// Create an estimator with custom weights.
    #[must_use]
    pub fn with_weights(weights: ConfidenceWeights) -> Self {
        Self {
            weights,
            source_overrides: FxHashMap::default(),
            calibration: CalibrationTracker::new(),
        }
    }

    /// Override the reliability score for a specific source.
    pub fn set_source_reliability(&mut self, source: ProposalSource, reliability: f64) {
        self.source_overrides.insert(source, reliability.clamp(0.0, 1.0));
    }

    /// Score a proposal given its source and context.
    #[must_use]
    pub fn score(
        &self,
        proposal: &Proposal,
        source: ProposalSource,
        counterexamples_addressed: usize,
        total_counterexamples: usize,
    ) -> ConfidenceScore {
        let weights = self.weights.normalized();

        let source_reliability = self
            .source_overrides
            .get(&source)
            .copied()
            .unwrap_or_else(|| source.default_reliability());

        let formula_complexity = score_complexity(&proposal.kind);

        let counterexample_coverage = if total_counterexamples > 0 {
            (counterexamples_addressed as f64) / (total_counterexamples as f64)
        } else {
            0.5 // neutral when no counterexamples available
        };

        let historical_success =
            self.calibration.success_rate_for_kind(&proposal.kind).unwrap_or(0.5);

        let breakdown = ConfidenceBreakdown {
            source_reliability,
            formula_complexity,
            counterexample_coverage,
            historical_success,
        };

        let value = weights.source_reliability * source_reliability
            + weights.formula_complexity * formula_complexity
            + weights.counterexample_coverage * counterexample_coverage
            + weights.historical_success * historical_success;

        ConfidenceScore::new(value, breakdown)
    }

    /// Record whether a proposal succeeded or failed, for calibration.
    pub fn record_outcome(&mut self, proposal: &Proposal, succeeded: bool) {
        self.calibration.record(&proposal.kind, succeeded);
    }

    /// Get the current calibration tracker (read-only).
    #[must_use]
    pub fn calibration(&self) -> &CalibrationTracker {
        &self.calibration
    }
}

impl Default for ConfidenceEstimator {
    fn default() -> Self {
        Self::new()
    }
}

/// Scoring strategy for ranking proposals.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum RankingStrategy {
    /// Rank by overall confidence score (highest first).
    ByConfidence,
    /// Rank by formula simplicity (simpler specs first).
    BySimplicity,
    /// Rank by expected impact (addresses more counterexamples first).
    ByImpact,
    /// Combined ranking: weighted blend of confidence, simplicity, and impact.
    Combined,
}

/// A proposal paired with its computed confidence score.
#[derive(Debug, Clone)]
pub struct ScoredProposal {
    /// The original proposal.
    pub proposal: Proposal,
    /// The computed confidence score.
    pub score: ConfidenceScore,
    /// Number of counterexamples this proposal addresses.
    pub counterexamples_addressed: usize,
}

/// Rank proposals according to a strategy.
///
/// Returns a new sorted vector with scored proposals. The input is not modified.
#[must_use]
pub fn rank_proposals(scored: &[ScoredProposal], strategy: RankingStrategy) -> Vec<ScoredProposal> {
    let mut sorted: Vec<ScoredProposal> = scored.to_vec();
    match strategy {
        RankingStrategy::ByConfidence => {
            sorted.sort_by(|a, b| {
                b.score.value.partial_cmp(&a.score.value).unwrap_or(std::cmp::Ordering::Equal)
            });
        }
        RankingStrategy::BySimplicity => {
            sorted.sort_by(|a, b| {
                b.score
                    .breakdown
                    .formula_complexity
                    .partial_cmp(&a.score.breakdown.formula_complexity)
                    .unwrap_or(std::cmp::Ordering::Equal)
            });
        }
        RankingStrategy::ByImpact => {
            sorted.sort_by(|a, b| {
                b.counterexamples_addressed.cmp(&a.counterexamples_addressed).then_with(|| {
                    b.score.value.partial_cmp(&a.score.value).unwrap_or(std::cmp::Ordering::Equal)
                })
            });
        }
        RankingStrategy::Combined => {
            sorted.sort_by(|a, b| {
                let a_combined = combined_rank_score(a);
                let b_combined = combined_rank_score(b);
                b_combined.partial_cmp(&a_combined).unwrap_or(std::cmp::Ordering::Equal)
            });
        }
    }
    sorted
}

/// Compute a combined ranking score blending confidence, simplicity, and impact.
fn combined_rank_score(sp: &ScoredProposal) -> f64 {
    let confidence_weight = 0.5;
    let simplicity_weight = 0.2;
    let impact_weight = 0.3;

    let impact_normalized = (sp.counterexamples_addressed as f64).min(10.0) / 10.0;

    confidence_weight * sp.score.value
        + simplicity_weight * sp.score.breakdown.formula_complexity
        + impact_weight * impact_normalized
}

/// Score the complexity of a proposal's formula. Simpler specs score higher.
fn score_complexity(kind: &ProposalKind) -> f64 {
    let spec_text = match kind {
        ProposalKind::AddPrecondition { spec_body } => spec_body.as_str(),
        ProposalKind::AddPostcondition { spec_body } => spec_body.as_str(),
        ProposalKind::AddInvariant { spec_body } => spec_body.as_str(),
        ProposalKind::SafeArithmetic { replacement, .. } => replacement.as_str(),
        ProposalKind::AddBoundsCheck { check_expr } => check_expr.as_str(),
        ProposalKind::AddNonZeroCheck { check_expr } => check_expr.as_str(),
    };

    // Heuristic: shorter specs are simpler. Also penalize logical connectives.
    let len_score = 1.0 - (spec_text.len() as f64 / 200.0).min(1.0);

    let connective_count = spec_text.matches("&&").count()
        + spec_text.matches("||").count()
        + spec_text.matches("==>").count()
        + spec_text.matches("forall").count()
        + spec_text.matches("exists").count();
    let connective_penalty = (connective_count as f64 * 0.1).min(0.5);

    (len_score - connective_penalty).clamp(0.0, 1.0)
}

/// Categorize a ProposalKind into a string key for calibration tracking.
fn kind_category(kind: &ProposalKind) -> &'static str {
    match kind {
        ProposalKind::AddPrecondition { .. } => "precondition",
        ProposalKind::AddPostcondition { .. } => "postcondition",
        ProposalKind::AddInvariant { .. } => "invariant",
        ProposalKind::SafeArithmetic { .. } => "safe_arithmetic",
        ProposalKind::AddBoundsCheck { .. } => "bounds_check",
        ProposalKind::AddNonZeroCheck { .. } => "nonzero_check",
    }
}

/// Tracks predicted vs actual success rates for calibration.
#[derive(Debug, Clone)]
pub struct CalibrationTracker {
    /// Per-category: (successes, total attempts).
    records: FxHashMap<&'static str, (u64, u64)>,
}

impl CalibrationTracker {
    /// Create a new empty tracker.
    #[must_use]
    pub fn new() -> Self {
        Self { records: FxHashMap::default() }
    }

    /// Record an outcome for a proposal kind.
    pub fn record(&mut self, kind: &ProposalKind, succeeded: bool) {
        let category = kind_category(kind);
        let entry = self.records.entry(category).or_insert((0, 0));
        if succeeded {
            entry.0 += 1;
        }
        entry.1 += 1;
    }

    /// Get the success rate for a proposal kind, if any data exists.
    #[must_use]
    pub fn success_rate_for_kind(&self, kind: &ProposalKind) -> Option<f64> {
        let category = kind_category(kind);
        self.records.get(category).and_then(|&(successes, total)| {
            if total > 0 { Some(successes as f64 / total as f64) } else { None }
        })
    }

    /// Get success rate for a named category.
    #[must_use]
    pub fn success_rate(&self, category: &str) -> Option<f64> {
        self.records.get(category).and_then(|&(successes, total)| {
            if total > 0 { Some(successes as f64 / total as f64) } else { None }
        })
    }

    /// Get the total number of recorded outcomes.
    #[must_use]
    pub fn total_records(&self) -> u64 {
        self.records.values().map(|&(_, total)| total).sum()
    }

    /// Get all categories with their success rates.
    #[must_use]
    pub fn all_rates(&self) -> Vec<(&'static str, f64)> {
        self.records
            .iter()
            .filter_map(
                |(&cat, &(successes, total))| {
                    if total > 0 { Some((cat, successes as f64 / total as f64)) } else { None }
                },
            )
            .collect()
    }
}

impl Default for CalibrationTracker {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proposer::{Proposal, ProposalKind};

    fn make_proposal(kind: ProposalKind, confidence: f64) -> Proposal {
        Proposal {
            function_path: "test::f".into(),
            function_name: "f".into(),
            kind,
            confidence,
            rationale: "test".into(),
        }
    }

    fn precondition_proposal(spec: &str, confidence: f64) -> Proposal {
        make_proposal(ProposalKind::AddPrecondition { spec_body: spec.into() }, confidence)
    }

    // --- ConfidenceScore ---

    #[test]
    fn test_confidence_score_clamps_value() {
        let score = ConfidenceScore::new(1.5, ConfidenceBreakdown::default());
        assert!((score.value - 1.0).abs() < f64::EPSILON);

        let score_neg = ConfidenceScore::new(-0.5, ConfidenceBreakdown::default());
        assert!(score_neg.value.abs() < f64::EPSILON);
    }

    #[test]
    fn test_confidence_score_preserves_valid_value() {
        let score = ConfidenceScore::new(0.75, ConfidenceBreakdown::default());
        assert!((score.value - 0.75).abs() < f64::EPSILON);
    }

    // --- ProposalSource ---

    #[test]
    fn test_source_default_reliabilities() {
        assert!((ProposalSource::Heuristic.default_reliability() - 0.6).abs() < f64::EPSILON);
        assert!(
            (ProposalSource::WeakestPrecondition.default_reliability() - 0.8).abs() < f64::EPSILON
        );
        assert!((ProposalSource::Llm.default_reliability() - 0.5).abs() < f64::EPSILON);
        assert!(
            (ProposalSource::CounterexampleGuided.default_reliability() - 0.75).abs()
                < f64::EPSILON
        );
        assert!((ProposalSource::SignatureBased.default_reliability() - 0.4).abs() < f64::EPSILON);
    }

    // --- ConfidenceWeights ---

    #[test]
    fn test_weights_normalize() {
        let weights = ConfidenceWeights {
            source_reliability: 1.0,
            formula_complexity: 1.0,
            counterexample_coverage: 1.0,
            historical_success: 1.0,
        };
        let norm = weights.normalized();
        let sum = norm.source_reliability
            + norm.formula_complexity
            + norm.counterexample_coverage
            + norm.historical_success;
        assert!((sum - 1.0).abs() < 1e-10, "normalized weights should sum to 1.0, got {sum}");
    }

    #[test]
    fn test_weights_normalize_zero_returns_default() {
        let weights = ConfidenceWeights {
            source_reliability: 0.0,
            formula_complexity: 0.0,
            counterexample_coverage: 0.0,
            historical_success: 0.0,
        };
        let norm = weights.normalized();
        let default = ConfidenceWeights::default();
        assert!((norm.source_reliability - default.source_reliability).abs() < f64::EPSILON);
    }

    // --- ConfidenceEstimator ---

    #[test]
    fn test_estimator_scores_proposal() {
        let estimator = ConfidenceEstimator::new();
        let proposal = precondition_proposal("x != 0", 0.9);
        let score = estimator.score(&proposal, ProposalSource::Heuristic, 1, 2);

        assert!(score.value > 0.0 && score.value <= 1.0);
        assert!((score.breakdown.source_reliability - 0.6).abs() < f64::EPSILON);
        assert!((score.breakdown.counterexample_coverage - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn test_estimator_with_source_override() {
        let mut estimator = ConfidenceEstimator::new();
        estimator.set_source_reliability(ProposalSource::Llm, 0.9);

        let proposal = precondition_proposal("x > 0", 0.7);
        let score = estimator.score(&proposal, ProposalSource::Llm, 0, 0);

        assert!((score.breakdown.source_reliability - 0.9).abs() < f64::EPSILON);
    }

    #[test]
    fn test_estimator_with_custom_weights() {
        let weights = ConfidenceWeights {
            source_reliability: 1.0,
            formula_complexity: 0.0,
            counterexample_coverage: 0.0,
            historical_success: 0.0,
        };
        let estimator = ConfidenceEstimator::with_weights(weights);
        let proposal = precondition_proposal("x != 0", 0.9);
        let score = estimator.score(&proposal, ProposalSource::WeakestPrecondition, 0, 0);

        // With only source_reliability weighted, score should match WP reliability
        assert!((score.value - 0.8).abs() < 0.01);
    }

    #[test]
    fn test_estimator_counterexample_coverage() {
        let estimator = ConfidenceEstimator::new();
        let proposal = precondition_proposal("x < len", 0.8);

        let score_all = estimator.score(&proposal, ProposalSource::Heuristic, 5, 5);
        let score_some = estimator.score(&proposal, ProposalSource::Heuristic, 2, 5);
        let score_none = estimator.score(&proposal, ProposalSource::Heuristic, 0, 5);

        assert!(score_all.value > score_some.value);
        assert!(score_some.value > score_none.value);
    }

    #[test]
    fn test_estimator_no_counterexamples_neutral() {
        let estimator = ConfidenceEstimator::new();
        let proposal = precondition_proposal("x != 0", 0.9);
        let score = estimator.score(&proposal, ProposalSource::Heuristic, 0, 0);
        assert!((score.breakdown.counterexample_coverage - 0.5).abs() < f64::EPSILON);
    }

    // --- score_complexity ---

    #[test]
    fn test_simple_spec_scores_higher_complexity() {
        let simple =
            score_complexity(&ProposalKind::AddPrecondition { spec_body: "x != 0".into() });
        let complex = score_complexity(&ProposalKind::AddPrecondition {
            spec_body: "forall i, 0 <= i && i < len ==> arr[i] > 0 && arr[i] < MAX".into(),
        });
        assert!(
            simple > complex,
            "simple spec ({simple}) should score higher than complex ({complex})"
        );
    }

    #[test]
    fn test_complexity_penalizes_connectives() {
        let no_connectives =
            score_complexity(&ProposalKind::AddPrecondition { spec_body: "x > 0".into() });
        let with_connectives = score_complexity(&ProposalKind::AddPrecondition {
            spec_body: "x > 0 && y > 0 && z > 0".into(),
        });
        assert!(no_connectives > with_connectives);
    }

    #[test]
    fn test_complexity_score_in_range() {
        let specs = vec![
            "x != 0",
            "a <= usize::MAX - b",
            "forall i, 0 <= i && i < n ==> arr[i] > 0",
            "x > 0 && y > 0 && z > 0 || w == 0",
        ];
        for spec in specs {
            let score = score_complexity(&ProposalKind::AddPrecondition { spec_body: spec.into() });
            assert!(
                (0.0..=1.0).contains(&score),
                "complexity score for '{spec}' should be in [0.0, 1.0], got {score}"
            );
        }
    }

    // --- CalibrationTracker ---

    #[test]
    fn test_calibration_empty_returns_none() {
        let tracker = CalibrationTracker::new();
        let kind = ProposalKind::AddPrecondition { spec_body: "x != 0".into() };
        assert_eq!(tracker.success_rate_for_kind(&kind), None);
    }

    #[test]
    fn test_calibration_tracks_success_rate() {
        let mut tracker = CalibrationTracker::new();
        let kind = ProposalKind::AddPrecondition { spec_body: "x != 0".into() };

        tracker.record(&kind, true);
        tracker.record(&kind, true);
        tracker.record(&kind, false);

        let rate = tracker.success_rate_for_kind(&kind).expect("should have data");
        assert!((rate - 2.0 / 3.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_calibration_separate_categories() {
        let mut tracker = CalibrationTracker::new();
        let pre = ProposalKind::AddPrecondition { spec_body: "x != 0".into() };
        let post = ProposalKind::AddPostcondition { spec_body: "result > 0".into() };

        tracker.record(&pre, true);
        tracker.record(&post, false);

        let pre_rate = tracker.success_rate_for_kind(&pre).expect("has data");
        let post_rate = tracker.success_rate_for_kind(&post).expect("has data");

        assert!((pre_rate - 1.0).abs() < f64::EPSILON);
        assert!(post_rate.abs() < f64::EPSILON);
    }

    #[test]
    fn test_calibration_total_records() {
        let mut tracker = CalibrationTracker::new();
        let kind = ProposalKind::AddPrecondition { spec_body: "x".into() };
        tracker.record(&kind, true);
        tracker.record(&kind, false);
        tracker.record(&kind, true);

        assert_eq!(tracker.total_records(), 3);
    }

    #[test]
    fn test_calibration_all_rates() {
        let mut tracker = CalibrationTracker::new();
        tracker.record(&ProposalKind::AddPrecondition { spec_body: "x".into() }, true);
        tracker.record(&ProposalKind::AddPostcondition { spec_body: "y".into() }, false);

        let rates = tracker.all_rates();
        assert_eq!(rates.len(), 2);
    }

    #[test]
    fn test_calibration_influences_scoring() {
        let mut estimator = ConfidenceEstimator::new();
        let good_kind = ProposalKind::AddPrecondition { spec_body: "x != 0".into() };
        let bad_kind = ProposalKind::AddPostcondition { spec_body: "result > 0".into() };

        // Record that preconditions succeed often, postconditions fail often
        for _ in 0..10 {
            estimator.record_outcome(&make_proposal(good_kind.clone(), 0.9), true);
            estimator.record_outcome(&make_proposal(bad_kind.clone(), 0.9), false);
        }

        let good_proposal = make_proposal(good_kind, 0.9);
        let bad_proposal = make_proposal(bad_kind, 0.9);

        let good_score = estimator.score(&good_proposal, ProposalSource::Heuristic, 0, 0);
        let bad_score = estimator.score(&bad_proposal, ProposalSource::Heuristic, 0, 0);

        assert!(
            good_score.value > bad_score.value,
            "precondition ({}) should outscore postcondition ({}) after calibration",
            good_score.value,
            bad_score.value
        );
    }

    // --- RankingStrategy ---

    fn make_scored(spec: &str, confidence: f64, cex: usize) -> ScoredProposal {
        let proposal = precondition_proposal(spec, confidence);
        let complexity = score_complexity(&proposal.kind);
        ScoredProposal {
            proposal,
            score: ConfidenceScore::new(
                confidence,
                ConfidenceBreakdown {
                    source_reliability: 0.6,
                    formula_complexity: complexity,
                    counterexample_coverage: 0.5,
                    historical_success: 0.5,
                },
            ),
            counterexamples_addressed: cex,
        }
    }

    #[test]
    fn test_rank_by_confidence() {
        let scored = vec![
            make_scored("x > 0", 0.5, 1),
            make_scored("y != 0", 0.9, 0),
            make_scored("z < len", 0.7, 2),
        ];
        let ranked = rank_proposals(&scored, RankingStrategy::ByConfidence);
        assert!((ranked[0].score.value - 0.9).abs() < f64::EPSILON);
        assert!((ranked[1].score.value - 0.7).abs() < f64::EPSILON);
        assert!((ranked[2].score.value - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn test_rank_by_simplicity() {
        let scored = vec![
            make_scored("forall i, arr[i] > 0 && arr[i] < MAX", 0.9, 1),
            make_scored("x != 0", 0.5, 1),
            make_scored("a > 0 && b > 0", 0.7, 1),
        ];
        let ranked = rank_proposals(&scored, RankingStrategy::BySimplicity);
        // "x != 0" should be simplest (highest complexity score)
        assert!(
            ranked[0].score.breakdown.formula_complexity
                >= ranked[1].score.breakdown.formula_complexity
        );
    }

    #[test]
    fn test_rank_by_impact() {
        let scored = vec![
            make_scored("x > 0", 0.9, 1),
            make_scored("y != 0", 0.5, 5),
            make_scored("z < len", 0.7, 3),
        ];
        let ranked = rank_proposals(&scored, RankingStrategy::ByImpact);
        assert_eq!(ranked[0].counterexamples_addressed, 5);
        assert_eq!(ranked[1].counterexamples_addressed, 3);
        assert_eq!(ranked[2].counterexamples_addressed, 1);
    }

    #[test]
    fn test_rank_combined() {
        let scored = vec![
            make_scored("x > 0", 0.5, 1),
            make_scored("y != 0", 0.9, 5),
            make_scored("z < len", 0.7, 0),
        ];
        let ranked = rank_proposals(&scored, RankingStrategy::Combined);
        // High confidence + high impact should rank first
        assert_eq!(ranked[0].counterexamples_addressed, 5);
    }

    #[test]
    fn test_rank_empty_input() {
        let ranked = rank_proposals(&[], RankingStrategy::ByConfidence);
        assert!(ranked.is_empty());
    }

    #[test]
    fn test_rank_single_element() {
        let scored = vec![make_scored("x != 0", 0.8, 2)];
        let ranked = rank_proposals(&scored, RankingStrategy::ByConfidence);
        assert_eq!(ranked.len(), 1);
    }

    #[test]
    fn test_rank_preserves_all_elements() {
        let scored = vec![
            make_scored("a > 0", 0.3, 1),
            make_scored("b > 0", 0.6, 2),
            make_scored("c > 0", 0.9, 3),
        ];
        for strategy in [
            RankingStrategy::ByConfidence,
            RankingStrategy::BySimplicity,
            RankingStrategy::ByImpact,
            RankingStrategy::Combined,
        ] {
            let ranked = rank_proposals(&scored, strategy);
            assert_eq!(ranked.len(), 3, "strategy {strategy:?} should preserve all elements");
        }
    }

    #[test]
    fn test_rank_does_not_mutate_input() {
        let scored = vec![make_scored("x > 0", 0.5, 1), make_scored("y != 0", 0.9, 0)];
        let _ranked = rank_proposals(&scored, RankingStrategy::ByConfidence);
        // Original should still have 0.5 first
        assert!((scored[0].score.value - 0.5).abs() < f64::EPSILON);
    }

    // --- Integration: end-to-end scoring + ranking ---

    #[test]
    fn test_end_to_end_score_and_rank() {
        let estimator = ConfidenceEstimator::new();

        let proposals = vec![
            precondition_proposal("x != 0", 0.9),
            precondition_proposal("forall i, 0 <= i && i < n ==> arr[i] > 0", 0.7),
            make_proposal(ProposalKind::AddPostcondition { spec_body: "result > 0".into() }, 0.6),
        ];

        let scored: Vec<ScoredProposal> = proposals
            .into_iter()
            .enumerate()
            .map(|(i, p)| {
                let score = estimator.score(&p, ProposalSource::Heuristic, i, 3);
                ScoredProposal { proposal: p, score, counterexamples_addressed: i }
            })
            .collect();

        let ranked = rank_proposals(&scored, RankingStrategy::ByConfidence);
        assert_eq!(ranked.len(), 3);

        // All scores should be in [0, 1]
        for sp in &ranked {
            assert!((0.0..=1.0).contains(&sp.score.value), "score {} out of range", sp.score.value);
        }

        // Should be sorted descending by confidence
        for w in ranked.windows(2) {
            assert!(w[0].score.value >= w[1].score.value);
        }
    }
}
