// trust-router/certus_backend/unsafe_classify.rs: Unsafe VC classification for certus dispatch
//
// tRust #360: Classification of unsafe-code VC sub-kinds, detection of
// separation logic assertions, and VC-to-class mapping.
//
// Author: Andrew Yates <andrew@andrewdyates.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use trust_types::*;

/// tRust #360: Classification of unsafe-code VC sub-kinds for certus dispatch.
///
/// When certus receives an unsafe-code VC, this classification determines which
/// ownership axioms and separation logic checks to apply.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub(crate) enum UnsafeVcClass {
    /// Raw pointer dereference — null, allocation validity, alignment checks.
    RawDeref,
    /// Raw pointer write — deref checks plus write permission and consistency.
    RawWrite,
    /// Transmute — layout compatibility, validity invariant, alignment.
    Transmute,
    /// FFI call — pointer arguments, heap invariant after call.
    FfiCall,
    /// Separation logic frame preservation — footprint disjointness.
    SepFrame,
    /// Separation logic heap precondition/postcondition.
    SepHeapCondition,
    /// Use-after-free detected by symbolic heap.
    UseAfterFree,
    /// Permission denied (read-only pointer write, freed pointer access).
    PermissionDenied,
    /// Generic unsafe operation (conservative flag).
    GenericUnsafe,
}

impl UnsafeVcClass {
    /// Human-readable label for SMT comments.
    pub(crate) fn label(self) -> &'static str {
        match self {
            UnsafeVcClass::RawDeref => "raw-deref",
            UnsafeVcClass::RawWrite => "raw-write",
            UnsafeVcClass::Transmute => "transmute",
            UnsafeVcClass::FfiCall => "ffi-call",
            UnsafeVcClass::SepFrame => "sep-frame",
            UnsafeVcClass::SepHeapCondition => "sep-heap",
            UnsafeVcClass::UseAfterFree => "use-after-free",
            UnsafeVcClass::PermissionDenied => "permission-denied",
            UnsafeVcClass::GenericUnsafe => "generic-unsafe",
        }
    }
}

/// tRust #360: Detect whether a VC is an unsafe separation logic assertion.
///
/// Returns `true` for VCs generated by trust-vcgen/separation_logic.rs which
/// use VcKind::Assertion with an `[unsafe:sep:*]` prefix.
#[must_use]
pub(crate) fn is_unsafe_sep_vc(vc: &VerificationCondition) -> bool {
    match &vc.kind {
        VcKind::Assertion { message } => {
            message.starts_with("[unsafe:sep:") || message.starts_with("[unsafe:sep]")
        }
        _ => false,
    }
}

/// tRust #360: Classify an unsafe-code VC into its specific sub-kind.
///
/// Parses the VcKind and assertion message to determine the exact unsafe
/// property being verified. Used by the SMT encoding to select appropriate
/// certus options and axiom templates.
#[must_use]
pub(crate) fn classify_unsafe_vc(vc: &VerificationCondition) -> Option<UnsafeVcClass> {
    // UnsafeOperation VCs from trust-vcgen/unsafe_vc.rs
    if let VcKind::UnsafeOperation { desc } = &vc.kind {
        let lower = desc.to_lowercase();
        if lower.contains("raw pointer dereference") {
            return Some(UnsafeVcClass::RawDeref);
        }
        if lower.contains("transmute") {
            return Some(UnsafeVcClass::Transmute);
        }
        if lower.contains("ffi call") {
            return Some(UnsafeVcClass::FfiCall);
        }
        if lower.contains("&raw mut") || lower.contains("&raw const") {
            return Some(UnsafeVcClass::RawDeref);
        }
        return Some(UnsafeVcClass::GenericUnsafe);
    }

    // Separation logic assertions from trust-vcgen/separation_logic.rs
    if let VcKind::Assertion { message } = &vc.kind {
        if !message.starts_with("[unsafe:sep:") && !message.starts_with("[unsafe:sep]") {
            return None;
        }
        if message.contains("use-after-free") {
            return Some(UnsafeVcClass::UseAfterFree);
        }
        if message.contains("permission denied") {
            return Some(UnsafeVcClass::PermissionDenied);
        }
        if message.contains("frame preservation") {
            return Some(UnsafeVcClass::SepFrame);
        }
        if message.contains("null check") || message.contains("allocation validity")
            || message.contains("alignment check") || message.contains("out-of-bounds")
        {
            return Some(UnsafeVcClass::RawDeref);
        }
        if message.contains("write permission") || message.contains("post-write") {
            return Some(UnsafeVcClass::RawWrite);
        }
        if message.contains("layout") || message.contains("validity")
            || message.contains("transmute")
        {
            return Some(UnsafeVcClass::Transmute);
        }
        if message.contains("ffi") || message.contains("null pointer argument") {
            return Some(UnsafeVcClass::FfiCall);
        }
        if message.contains("precondition") || message.contains("postcondition") {
            return Some(UnsafeVcClass::SepHeapCondition);
        }
        return Some(UnsafeVcClass::GenericUnsafe);
    }

    None
}
